### ISSUE TITLE
[Perception] Scene 2 - Term "audio description"

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-people-use-web-videos#102]
Maybe it might be worth to double-check if the term to be used is "audio description" as in WCAG or "description of visual information" as in EOWG resources. This might be a question that will be raised by the EO. 

I would also rephrase the following text a bit to make it more easy to understand: 
"Many use audio description tracks when they are provided by video content authors. Audio descriptions often use pauses in the audio track to describe the scenes, characters, and other visual information in the video."

**Comment by nitedog** [comment]
This scene has been rewritten entirely; please re-review.
