### ISSUE TITLE
[Cognitive] Scene 1 Audio - Wording Tweak

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#105]
Maybe this will flow better...
Current:

> Cognitive and learning disabilities is an umbrella term for a large spectrum of differences and disabilities. They affect how people store, retrieve, or use information, and many do not affect overall intelligence.

Suggested:

> Cognitive and learning disabilities is an umbrella term for a large spectrum of differences and disabilities that affect how people store, retrieve, or use information. Many of these disabilities do not affect overall intelligence.

**Comment by nitedog** [comment]
Changed as suggested.
