### ISSUE TITLE
[Cognitive] Scene 6 Audio - Suggested reword

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#106]
Trying to improve flow and structure.

Current:

> Web browsers and apps can provide lots of support; for example, by providing options to store previous entries and automatically fill form fields, or by providing options to avoid pop-up windows and animations. Websites and apps need to be programmed and designed to support such settings; for example, to label form fields.

Suggested:

> Web browsers and apps can support by providing options to store previous entries and automatically fill form fields, or by providing options to avoid pop-up windows and animations. However, websites and apps need to be designed and programmed to support such settings; for example, by properly labeling form fields.

**Comment by nitedog** [comment]
This scene was rolled into prior scenes to make this script easier to follow.
