### ISSUE TITLE
[Cognitive] Scene 5 Audo - Drop "For Example"

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#107]
Example of where "For Example" is not needed.

Current:

> Or, people might have difficulty focusing for long periods of time and might be easily distracted; for example, by pop-up windows and by automatically playing sounds and animations.

Suggested:

> Or, people might have difficulty focusing for long periods of time and might be easily distracted by pop-up windows or automatically playing sounds and animations.

**Comment by nitedog** [comment]
Changed as suggested.
