### ISSUE TITLE
[Cognitive] Scene 7 Audio - Rewording

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#108]
Better flow on the first sentence.
Current:

> Some people with cognitive and learning disabilities might affect only some functions and not others. For example, some people on the autism spectrum can carry out complex tasks such as data entry while experiencing barriers with verbal communication.

Suggested:

> For some people, cognitive and learning disabilities might affect only some functions and not others. For example, some people on the autism spectrum can carry out complex tasks such as data entry while experiencing barriers with verbal communication.

**Comment by nitedog** [comment]
This scene was dropped entirely.
