### ISSUE TITLE
[Cognitive] Scene 9 Audio - Flip the order

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#109]
Seems like the message is a bit out of order on this scene. Maybe something like this will work better... (also fixing type and/are)
Current:

> Websites and apps that are predictable and consistent and typically easier to use. For example, some people might experience difficulty orienting themselves to a new layout and visual design, or with learning the new keystrokes they need to use for interacting with the new design.

Suggested:

> Some people may experience difficulty orienting themselves to a new layout and visual design, or with learning the new keystrokes needed to interact with the new design. Websites and apps that are designed to be consistent and predictable are typically easier to use.

**Comment by nitedog** [comment]
Changed as suggested.
