### ISSUE TITLE
[physical] Scene 6 Audio - example doesn't match issue

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#110]
Current:

> Yet some people might rely solely on using pointing devices such as a mouse, joystick, trackball, steering wheel, or touch screen to type. For example, by using an eye-tracking system to type on an on-screen keyboard. The system detects eye movement to move the mouse pointer, and detects eye blinks to initiate mouse clicks.

In this scene it starts with describing people that rely solely on using a device such as a mouse joystick, trackball... etc. Then the example is a person that is not using a physical device, but using eye-tracking. Maybe this isn't supposed to be an example of the devices in the previous sentence. Either way it doesn't quite fit.

**Comment by nitedog** [comment]
This scene has been dropped or rewritten entirely; please re-review.
