### ISSUE TITLE
[physical] Scene 7 Audio - Reword to clarify

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#111]
Current:

> Some people might not be using a keyboard nor a pointing device to type, and rely on speech input instead. While speech input uses the keyboard interface in the background, websites and apps need to be programmed and designed to support speech input. For example, so that the name of a button in the software code matches the name displayed to the user. 

Suggestion:

> Some people do not use a keyboard or pointing device to type, but rely on speech input instead. Websites and apps need to be programmed and designed to support speech input. For example, to be functional, the name of a button in the software code should to match the name displayed to the user.

**Comment by nitedog** [comment]
This scene has been rewritten entirely; please re-review.
