### ISSUE TITLE
[physical] Scene 1 Audio - More uniform start

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#112]
To be more like the other video scripts, I am wondering if the Physical script needs to start with just a sentence or two background overview of physical disabilities. Maybe something like the following which is part of what is in the summary of the physical page from the resource...

> Physical disabilities, sometimes called “motor disabilities”, are disabilities that include weakness and limitations of muscular control, limitations of sensation, joint disorders, pain that impedes movement, and missing limbs.

**Comment by nitedog** [comment]
Changed as suggested.
