### ISSUE TITLE
[speech] Scene 4 Audio - Reword

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#113]
Remove "For example" from the sentence as it is not needed.

Current:

> Some people do not speak at all, for example because they are Deaf, have injured or no vocal organs, or because of another physical condition.

Suggestion: 

> Some people do not speak at all because they are Deaf, have injured or no vocal organs, or because of another physical condition.

**Comment by nitedog** [comment]
Changed as suggested.
