### ISSUE TITLE
[speech] Scene 5 Audio - Telephone applicable? Reword

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#115]
Not sure that telephone services count as web or application accessibility. This is a fine line to walk. Maybe refer more to websites or applications that may require speech input. Here is a suggested reword.

Current: 

> Using speech alone is barrier for many people; for example, when telephone services and online applications, such as customer support, rely on automatic speech recognition without alternative ways for communication.

Suggested:

> Websites or applications that require speech input can a barrier for some people; for example, when online applications such as customer support systems rely on automatic speech recognition without providing an alternative way for communication.

**Comment by nitedog** [comment]
Changed as suggested.
