### ISSUE TITLE
[speech] Scene 6 Audio - Reword for flow

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#116]
Current: 

> Some people use assistive devices to generate speech, which might also not work well with automatic speech recognition either. For example, some use “speech generated by a computer” [speech synthesis coming from a computer, sounding like that of Stephen Hawking] or devices like an electrolarynx, which “converts vibrations on the throat to sound” [speech coming from an electrolarynx device].

Suggested:

> Other situations that may be problematic with automatic speech recognition functionality are when people use assistive devices to generate speech. Examples are using “speech generated by a computer,” [speech synthesis coming from a computer, sounding like that of Stephen Hawking] or devices like an electrolarynx, which “converts vibrations on the throat to sound.” [speech coming from an electrolarynx device]

**Comment by nitedog** [comment]
Changed as suggested.
