### ISSUE TITLE
[visual] Scene 4 Audio - Add Constancy for the magnification strategy

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#119]
People using screen magnification rely on visual cues and I think we should mention consistent design as well as it is one of the most important factors for supporting people that must use large factor magnification.

Current:

> People only see small parts of the screen at a time, and rely on visual cues to orient themselves and navigate through the content.

Suggested:

> People only see small parts of the screen at a time, and rely on visual cues or **_consistent design_** to orient themselves and navigate through the content.

**Comment by nitedog** [comment]
Changed as suggested.
