### ISSUE TITLE
[visual] Scene 7 Audio - Color Blind and Deficiency

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#120]
If I remember from other resources I think we say color blind and color deficient. We will need to look for how we have referenced this condition in the past.

Current:

> Many people see colors differently, which is commonly referred to as color blind.

Suggested:

> Many people see colors differently, which is commonly referred to as color blind or color deficiency.

**Comment by nitedog** [comment]
The actual reference page lists "Color vision deficiency" as one of the conditions but I'm not sure we want to use the term "deficient/deficiency" in the video? Happy to discuss.
