### ISSUE TITLE
[Cognitive] Scene 2

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#124]
Specifically mentioning only a handful of disabilities feels problematic in this script, as there are so many on the examples list in the original resource. Would it be easier to focus on how the barriers are removed rather than the disabilities themselves?

**Comment by jade-mc** [comment]
I like how this has been put together with the personas though, it's cleverly done. 
Perhaps scene 8 needs more context?I read it first and thoguht it seemed out of place and it took a couple of reads for me to understand why it was there.

**Comment by nitedog** [comment]
Previous scene 6 was rolled into earlier ones, and 7 and 8 were completely removed, to better focus this script as suggested here.
