### ISSUE TITLE
[visual] Scenes 4-6

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#125]
Scenes 4-6 are relying on the same point (at the end of scene 6, _Websites and apps need to be programmed and designed to adapt to different text sizes and line spacing without the text overlapping, getting cropped, or creating difficult scrolling._) but to make this clearer, could that go first, just before scene 4?

**Comment by nitedog** [comment]
Actually, this only referred back to 5-6 but point taken -- this sentence has been moved to the front of scene 5 and the end of scene 4 has also been adjusted to make the leap more apparent.
