### ISSUE TITLE
[Yun] Scene 1 - don't care for "not really disabled"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#126]
Starting the script with the following doesn't feel right: "I’m not really disabled but see less and hear less than before, and so." 

Though it may be how some people feel, it feels like it may offend those who do identify as disabled (or come across as a bad thing to identify as such). Would just focus on that fact that he recognizes he's aging.

**Comment by nitedog** [comment]
Changed to "I see less and hear less than in my young days. Also, my hands shake a little.".
