### ISSUE TITLE
[Yun] Scene 6 - "stored in web browser" doesn't seem realistic

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#128]
For these lines: 

> But my daughter told me not to do this, I’m not really sure why. She said it’s already stored in my web browser. It’s true – all I have to do is select the address or credit card numbers without typing them each time. 

It doesn't feel like Yun would know this distinction (or even the term "web browser") unless he worked in tech.

**Comment by nitedog** [comment]
Changed this part to now say:

> I can also store my address and credit card numbers because I have difficulty remember them. But somehow the computer remembers my information for this website -- all I have to do is select the address or credit card numbers without typing them each time.
