### ISSUE TITLE
[Noor] Scene 4 - Why point out Braille difficulty?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#130]
The latter portion that says Noor is having difficulty learning Braille may come across wrong to advocates of keeping Braille around. If we're trying to showcase that learning and reading Braille aren't automatic, I think we can say that such as, "It hasn't been easy to learn Braille and distinguish the dots on my display but I do my best..." I fear right now it's sort of left hanging and gives the impression that everyone will have a hard time with it.

**Comment by nitedog** [comment]
Changed this part to now say;

> It's difficult to learn something new at first but I'm slowly getting used to distinguish the small dots popping up on the display with my fingertips -- it still takes me a while to read difficult words but I'm getting there!
