### ISSUE TITLE
[Noor] Scene 5 - Wrong impression that websites working well for magnification mean working well for Braille displays

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#131]
I'm not sure I see the correlation between websites that are designed well for magnification also working well for Braille displays. I actually often see people so focused on screen readers (and, thus, Braille display output) that they forget about other disabilities (or are unaware of them). Since magnification's usability is primarily based on the visual layout and screen readers are highly based on code structure, I'm not sure we should tie the two together in this way.

**Comment by nitedog** [comment]
Changed this part to now say:

> Some websites and apps work well with magnification and also on my braille display. For example, my school website uses different styles for each headings level, which help me navigate on my screen. These heading levels also get indicated on my braille display.
