### ISSUE TITLE
[Luis] Scene 4 - "long and complicated forms" doesn't feel like Luis's voice

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#132]
Based on the other language in the script, I don't think Luis would say, "I also have trouble filling in these long and complicated forms." Maybe we should describe them instead like "I don't like when pages have all these little boxes to fill in - I like when it just asks me a few questions at a time..."

**Comment by nitedog** [comment]
Changed to "I often have trouble understanding what I need to type in the boxes to get the ticket".
