### ISSUE TITLE
[Ilya] Scene 2 - Right way to describe a screen reader?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#136]
I'm always hesitant to describe a screen reader as something that "reads what's on the screen" because it gives the wrong impression & can impede people understanding SR accessibility. 

Even if a screen reader user doesn't understand the technical implementation of a screen reader, I think someone who works at a corporation like Ilya does would at least know that things don't read because of the code. Thus, I propose we alter or add something about "code" in the description of the screen reader.

**Comment by nitedog** [comment]
Changed to "It's a software that presents information on the screen in audio or in braille".

Also added "in the code" at the end of the next sentence, to read: "This includes text but it also indicates the headings in a document, lists and how many list items they have, and tables and controls and such in the code" (this sentence may seem more complex than when it is spoken by someone).

**Comment by MicheleAWilliams-A11y** [comment]
This helped, though I suggested a bit more re-write in #158

**Comment by nitedog** [comment]
Addressed separately.
