### ISSUE TITLE
[Alan] Scene 2 - Change "proper keyboard" to something more neutral

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#138]
Saying "proper" keyboard seems to imply there are versions that are "improper". I would just describe the type of keyboard that most helps.

**Comment by nitedog** [comment]
Changed to "A keyboard that I can use is really important to me".

**Comment by MicheleAWilliams-A11y** [comment]
Agree, this helps & fixes the issue
