### ISSUE TITLE
[Alan] scene 7. 

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#146]
I'm worried here that Alan's being quite negative about speech control software, it's difficult to get people to stick with it so I wouldn't want us to inadvertently reinforce that. 

_But it’s really hard to learn a new way of working after so many years – I make mistakes while dictating and it takes me longer to fix them than to just type what I wanted to say. Also, many websites and apps have incorrectly coded buttons and menus so when I say......_ 

Suggest something like, 'It is really tricky to learn a new way of working after so many years, but I've been patient with it and I'm getting used to it slowly. The most difficult thing is when websites and apprs are incorrectly coded...

**Comment by nitedog** [comment]
Rephrased entire section to now read:

> I recently started using speech control software as well. It allows me to dictate text instead of typing, and to say certain commands instead of clicking. It's really hard to learn a new way of working after so many years but I've been patient with it and am slowly getting used to it. The most difficult thing is when websites and apps are incorrectly coded, so when I say "click search" or "click next" it doesn't work as expected. It holds me up trying to figure out what went wrong and find a work around.
