### ISSUE TITLE
[Noor] Scene 4

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#148]
You can absolutely ignore this, but it'd be great to take aim at how expensive refreshable braille displays are here...

**Comment by nitedog** [comment]
EOWG typically avoids discussion of cost for a variety of reasons and it would also seem odd discussing this only here and not for other assistive technologies too. I suggest this "disability tax" topic is out of scope for these particular videos but happy to discuss further.
