### ISSUE TITLE
[Lee] Scene 5 Audio - Wording edit

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#156]
[strong]
Needs some wording changed for clarification.

Current:

>... Or, when they use charts without providing legends, so that I can associate the bars or lines without relying on color alone. 

Suggestion:

>... Another example is when charts are used without providing legends. I can't associate the bars or lines with data when I have to rely on color alone.

**Comment by nitedog** [comment]
Used this suggested approach but adapted to address issue #162:

> Another example is when charts don't have symbols in addition to the colors for lines and bars -- I can't identify them from color alone.
