### ISSUE TITLE
[Ilya] Scene 2 - Make a bit more conversational & explain the keyboard

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#158]
It doesn't feel like a non-technical person (e.g., accountant) would describe a screen reader using terms like "digital content". Overall this felt a bit jargon-y. It also doesn't describe that a screen reader works with a keyboard (which would then help segue to Scene 3 where Ilya talks about finding it hard to learn new systems).

Based on how I've heard other blind folks describe screen readers to sighted folks, how about something like:

> On my computer I use software called a "screen reader". It has certain keyboard commands I use to have it describe the information on the screen. It announces these as audio that I listen to, and even into Braille that I can read on a special electronic Braille device. Everything about each element is described based on what's in the code - like the headings in a document, lists and how many list items they have, and tables and form controls. It’s like a sighted assistant describing everything on the screen to me -- only much quicker [brief pause to listen to a short slice of screen reader at moderately high speed while the video is being shown in the visuals]. People are surprised at how fast my speech can go, but I listen to this all day everyday over many years. I suppose it's the same as how fast someone can read with their eyes.

**Comment by nitedog** [comment]
Slightly edited (mainly to shorten and match the remaining text) to:

> On my work computer, I use software called a "screen reader". It describes information on the screen in audio or in braille. It indicates everything that's in the code -- like the headings in a document, lists and how many list items they have, and tables and form controls. It's like a sighted assistant describing everything on the screen to me -- only much quicker [brief pause to listen to a short slice of screen reader at moderately high speed while the video is being shown in the visuals]. People are surprised at how fast I set the speech but I listen to this all day.
