### ISSUE TITLE
[Ilya] Scene 4 - Stronger ending/tie to previous point

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#159]
The prior scene talks about switching screen readers and this scene then talks about switching applications to online from desktop. Right now it's not clear how all these points are tying together nor what made the new online software "accessible" (which would go beyond the scope of this video to explain).

Perhaps this scene could end by saying more explicitly that the new online applications are, say, "compatible with the screen reader I use for my computer" and even add "so I didn't have to learn yet another screen reader". Just trying to get something that would tie all the points together...

**Comment by nitedog** [comment]
This sounds as if changing screen reader would make the applications work, whereas the point is that these applications often don't work with screen readers at all. 

Changed this and the prior scenes to:

> Some screen readers, like the one on my work computer, are quite complex and take a lot of time to learn all the keyboard commands. I prefer the screen reader on my mobile phone, which is much easier to use. I can also just speak most actions I want on my phone instead of all the typing and swiping. If I could, I would use my phone for everything but I can't access my company network with personal devices.
> ---
> A few years ago the company I work for changed all desktop applications to online applications. I was concerned about that change because online applications often don't work well with screen readers, especially complex applications like the online spreadsheets, presentations, and documents that I need to use and edit. Luckily, the company paid attention to that aspect during procurement and selected a provider that ensured accessibility.
