### ISSUE TITLE
[Lee] Scene 4 - Fantasy football example unclear

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#161]
I'm unclear what the visuals would look like for the Fantasy Football app. 

Firstly, is this "American Football" or the "real" football? :-) 

For American Football, the type of display that's described wouldn't make sense -- even if you are trying to compare your roster with someone else's, you would just display names and stats as text (as in photo attached). It's difficult to see all of your own players and their stats in one view (there's typically at least 12 per team) let alone have them alongside other players from other teams on the same screen. Thus, players are usually shown with their photo and NFL team name written out (as in the attached photos). Also since they're drafted from actual NFL teams, it's more likely you'll see the NFL team name than your fantasy team's name referenced.

For Premier League, I found a few screens that use player jerseys - is this the type of view that was envisioned? These are their actual team jerseys though, not the jersey of the fantasy team as seems to be described in the text. If this is what is meant, however, what would be the other symbol used to distinguish these jerseys and how would it help (and not clutter)? 

Overall I think most apps use text and player's faces and not colors/jerseys; thus, this example likely needs a rewrite...
![FF_Screen1](https://user-images.githubusercontent.com/84785057/188509213-dc83230d-93c4-4e3c-928a-66a96c2f2701.jpg)
![FF_Screen2](https://user-images.githubusercontent.com/84785057/188509216-db7c6267-62ae-4153-9898-e93600f23525.jpg)
![FF_Screen3](https://user-images.githubusercontent.com/84785057/188509218-535ebfd1-b7cf-4846-a0ba-4d0c447579b3.jpg)
![FF_Screen4](https://user-images.githubusercontent.com/84785057/188509219-b1145578-fc8e-49bf-89ce-edf58b89d6da.jpg)

**Comment by jade-mc** [comment]
Absolutely proper football Michelle! 
I think Shadi probably had that FIFA interface in mind maybe. 
I don't see this as much of an issue, the visual would only be a brief look at a football top with a team logo on it, right?

**Comment by nitedog** [comment]
This example comes directly from the reference page. I agree that it probably applies to older types of games but also agree with Jade that it doesn't really matter much, as long as people get the point about redundant coding.

Keeping this issue open for further perspectives.

**Comment by iadawn** [comment]
We kept the reference to football deliberately vague to allow for users to interpret as they saw fit. I think there are a couple of things from the examples you show @MicheleAWilliams-A11y that would be problematic. The shirts on the page is possibly one, strength of schedule is using colour for something... not sure what.

The goal with this was to provide an example that wasn't just about work or buying something online. There may be other more suitable examples though.

**Comment by nitedog** [comment]
Lee now says the following:
> Not relying on color alone is important for other websites and apps too! For example, my favorite fantasy football app has a symbol for each team on the jersy of the players, in addition to color. This helps me spot the players on my team more quickly, not just by reading the names under each player. Unfortunately, my friends are not so sold on this app yet and I have some more convincing to do.

The visuals for this are:
> We see Lee in a casual enviroment (same or different setting, depending on filming logistics), who is now playing a fantasy football game. We see the players of the two teams have differently colored jerseys with different symbols as well. Lee is very engaged in the game (e.g. biting his tongue, moving around with the game controller, ...).

That is, we are not seeing the roster like in the top images but more a match being played like in the bottom images. The jerseys would have patterns or symbols, like many of these image, which is another example of redundant coding. Besides shopping and charts, I think an online games example is a good illustration of the issue.
