### ISSUE TITLE
[Lee] Scene 5 - Graph example incorrect

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#162]
Currently the graph is explained as being an issue because it doesn't have a legend. This wouldn't make it inaccessible for color reasons - this would make it inaccessible to everyone because no one would know what the graph indicates at all without a legend. 

Instead the issue is when the differences in the graph are only color and not things like symbols or differing fill effects, as in the examples in this article: https://medium.com/seek-blog/press-the-pink-button-designing-for-colour-blind-users-17d261755ee1

So we'll want to reword to say that the graphs only use color.

**Comment by nitedog** [comment]
Changed to "Another example is when charts don't have symbols in addition to the colors for lines and bars -- I can't identify them from color alone."
