### ISSUE TITLE
[Lee] Scene 5 - Suggested rewording

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#163]
This phrasing feels a bit odd to me: "My team knows differently but many suppliers we work with still don’t..."

Perhaps, "My team has learned to be mindful of this but many suppliers we work with unfortunately don't..."

**Comment by jade-mc** [comment]
Suggest, my team knows/has learned to be careful with this. 
Mindful is quite a complex word.

**Comment by nitedog** [comment]
Changed to "My team is usually careful about this but sometimes suppliers we work with aren't [sigh]."
