### ISSUE TITLE
[Noor] just a couple of cosmetic bits

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#164]
Scene 2, delete 'meanwhile' 
Scene 3, I think 'This is why' isnt' needed here, it isn't clear what it's connected to in the previous scene, and if it is connected to the tactile sign point and how it might be quite a slow form of communication, then that might be seen as a a bit negative.
Scene 4, slowly getting used to distinguishing.

**Comment by nitedog** [comment]
Adjusted accordingly (noting the changes made to address issue #167).
