### ISSUE TITLE
[Noor] Overall - Think this needs rewriting

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#167]
Noor's story in the written version has a lot more personal details (e.g., fashion school) and different examples than what's in this video script. It also doesn't include tactile signing. I don't recall why we have that in our script but I wonder if it's okay to have such a big difference here? (I know we've been deviating a bit along the way, but this feels like a big one because we'll need to explain and demonstrate this.) 

Nevertheless, overall the current script doesn't feel like a user story or day-in-the-life as much as just details about the tools and techniques. It also doesn't sound like a teenager (Shadi didn't get into full character here - tee hee). It may be presumed that Noor will present like a teenager visually, but the interpreter will be talking for them so that won't come through non-visually and would be better said explicitly (for instance, the "school website" kinda comes out of nowhere).

Lastly, even prior to re-reading the written script I felt this one needed a better flow, more descriptions (such as of the Braille device), and differing Web examples than headings (which are mentioned twice). Also, saying that digital tech allows for communicating "more freely" starts to counter how we explained sign language in the first video as is its own language distinct from written & spoken languages. 

It's difficult to put each of these into a separate ticket so I just did a rewrite here and maybe this can be copied in a Pull Request so people see the Diff.

**Suggested Revisions**

Scene 1: Hi! I’m Noor, a high school senior at my School for the Deaf. I’m deafblind. I was born deaf and have progressive vision loss which means I can still see some objects if they're large and up-close, but I see less and less each year.

Scene 2: I learned [American/British/...] sign language as a child but now I can’t see when someone signs back to me. So if I'm in-person with someone who signs or an interpreter, I adapted to using _[name of tactile sign; for example, “hands-on-signing”]_, which is a form of tactile signing. _[briefly describe how it works; for example, “I place my hands over the hands of my interpreter, to understand what they are signing”.]_ But this doesn't work for video and I can't see enough to lip read.

Scene 3: This makes my phone and school computer even more important for me. Most things are written, like stuff on our school website and apps with chat features, so I'm able to stay connected. On my phone and computer I use software called "magnification". It makes the content X times bigger, like using a magnifying glass, and I use my mouse or finger to go back and forth across the screen to read what's there. Most times pages are easy to follow, especially when they have headings and things are separated like the navigation always at the top and in a different color. One thing I hate though is when I have to put my mouse over something to read that little tooltip. My mouse doesn't work the same as people who aren't using magnification so it's hard to see that type of text - or even know it's there!

Scene 4: Oh, and I'm learning to use Braille, too. Braille are those dots that you read with your fingers, and I have a really cool device called a "refreshable Braille display". It's a computer and I can navigate to apps and Webpages by typing in Braille on the special keyboard, then read the information from those apps and pages into Braille characters in a row on the device. I can also type out things like my papers and it means I only need the one device - well, once I get fully used to it! Learning a new language and a new way to use a computer isn't always easy! But I'm getting better at it and I know it will make life easier when I go off to college and have lots of reading and writing to do. 

Scene 5: Actually I usually can get to everything I need either using the Braille display or looking on my phone, but sometimes a bad design gets in the way. Like when I need to look up the bus schedule to meet up with my friends, that table really doesn't work well when I zoom in on my phone. And forget about trying to read it in Braille -- I can't tell what row or column I'm in and it just jumps all over the place! Honestly it makes me nervous because I can't as easily ask for help from people around me while I'm out, so I've been learning how to speak up and ask companies for more accessible apps and sites to help me stay independent. I'll be in college next year and I know if I can use my technology like I should be able to, I can accomplish all my goals and live exactly as I want to.

**Comment by nitedog** [comment]
Adopted much of this rewrite but with minor adaptations to keep it simpler (eg. hover, chat, magnification on mobile, etc. would all need further explanation).
