### ISSUE TITLE
[Preety] Overall - Doesn't sound like a child's voice

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#169]
I don't have capacity to offer a rewrite for this one, but overall this doesn't sound like the child/teen that we're trying to represent with this. 

In particular, these caught my eye:

"...same pace as others..."
"Thankfully, our school uses..."
"They change it immediately when I remind them..."
"...browser settings..."
"Good articles have more spacing, headings and structure..."

I think you can make these sound a bit more common and less formal or technical; that will help sell this as a relatable character.

**Comment by nitedog** [comment]
Took a pass at simplifying these and other places.
