### ISSUE TITLE
[Yun] Scene 1 & 2 - Update introduction

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#170]
As mentioned in ticket #168, I think all the user stories post-Martine could use more personalizing in the intro. For Yun in particular who represents someone aging but necessarily someone who identifies as disabled (at least that's how I read this) perhaps he talks more about being a retiree and we learn about his body changes throughout.

So his opener might be something like, "Hello! I'm Yun. I'm a retired architect and professor. Life moves slower now that I'm retired, and I think my body does too [laughs]!" Then throughout the script he just describes what he needs rather than saying it directly; e.g., "I can't see it when it's small".

**Comment by nitedog** [comment]
Made changes accordingly (see also changes listed in issue #168).
