### ISSUE TITLE
[Ian] :18-:39 Luckily

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-people-use-web-videos#171]
Why is this a lucky thing? Isn't it planned and part of Ian's accommodation? 
Maybe instead "My administrator has agreed to ..."

**Comment by nitedog** [comment]
Dropped "Luckily" from that sentence and added "usually" later on, to emphasize that this is a workaround and a less favorable solution:

> Our administrator usually shows me the changes before an update is installed on my computer to avoid surprises.
> But once I was also stopped from working because I got this very scary message [...]
