### ISSUE TITLE
[Ilya] 1:06 - 1:37

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-people-use-web-videos#172]
Again, the use of the word "Luckily" seems to imply that the employer has gone above and beyond. Providing usable tools to staff should not be a matter of luck in my opinion. (Even though that is sadly still the fact that it depends on luck) Also it is not always possible to "select an accessible provider" since accessible versions don't exist for some kinds of tools 
Maybe something like
I am glad that my company is committed to inclusive procurement practices and selected the the most accessible option.

**Comment by nitedog** [comment]
Changed to "I'm glad that my company paid attention to that aspect during procurement and found a provider that ensured accessibility".
