### ISSUE TITLE
[Alan] Move some content down

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-people-use-web-videos#182]
"While I can use a keyboard and mouse, I can’t use them for long periods because it’s tiring. It’s particularly tiring to keep switching between keyboard and mouse – or, my joystick. "

I feel like this text needs to be moved to section 7, right before you talk about using the speech control software as a way to explain why he has started using the speech control software.   

The flow that makes sense to me would be:
1. Meet Alan
2. Introduce his hardware tech setup that works for him (i.e keyboard, joystick setup and maybe iPad too)
3. Using keyboard navigation and challenges
4. finds it tiring so learning Speech control software and challenges

**Comment by nitedog** [comment]
Moved this sentence from seq 4 to seq 7, and edited slightly for better flow.
