### ISSUE TITLE
[Preety] 2nd scenario audio: Remove myths about dyslexia

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#183]
**[HIGH PRIORITY]**

1. Remove "sometimes letters or entire words appear differently to me, and it takes me longer to process them." This phrase must be removed to avoid reinforcing the myth that dyslexia is a problem with vision. It is not.

2. Make clear that dyslexia is not simply a problem of being slower at reading and writing. Replace “I couldn’t read or write as quickly as others in my class” with wording that emphasizes Preety’s struggles with reading and spelling are not related to her intelligence or willpower/effort.

**COGA's suggested rewording for 2nd scenario audio:**
"Apparently, many people have some form of dyslexia. I had big problems when I started with school [DELETE: because I couldn’t read or write as quickly others in my class. I thought it was me.] [ADD: At first, I could not understand why it was so impossible for me to learn how to read and spell even though I’m bright and was trying my best.] But then a doctor diagnosed dyslexia [DELETE: – sometimes letters or entire words appear differently to me, and it takes me longer to process them.] [ADD: Now I know why it was not working for me.”]

In case helpful, here is COGA's consolidated feedback on the Preety script, with tracked changes:
https://docs.google.com/document/d/17nVmc7-9Whv0jtwVWNaX_svGC-asP9YBrU_BsfxnN80/edit?usp=sharing

**Comment by bakkenb** [comment]
+1 to being clear the struggle is not a vision issue.

**Comment by nitedog** [comment]
Is there any possibility to describe some of the implications of dyslexia? Preety says "now I know why it was not working for me" but I feel the viewers are left with little explanation of what dyslexia is.

**Comment by julierawe** [comment]
Three suggestions in response to this follow-up question:

**1. Add more detail on how dyslexia affects Preety's reading and writing:**

> “Now I know why it’s so hard for me to read and write. I can not recognize or sound out written words even though I use those same words in conversation all the time. Dyslexia also affects my spelling and my reading comprehension. It often takes so long to figure out the individual words I’m reading, and then it’s hard for me to remember how the words in a sentence fit together as a meaningful unit.”

**2. Add how dyslexia affects Preety's memory:**

> "Because of the cognitive issues that have caused my dyslexia, I have a very uneven memory. I can remember facts and ideas better than anyone else I know. But I can not remember what things looked like, directions, how to spell my surname, my telephone number, phone codes, let alone passwords — although I know other dyslexics have different issues from me." 

**3. Note that not every dyslexic struggles in the same way.** See last half-sentence above: "Although I know other dyslexics have different issues from me."

In case helpful, here are all of COGA's responses to EO's follow-up questions:
https://docs.google.com/document/d/1m1piIXXGPtQeRNjYpch3MMgFP1uy3GBA0XbgLUqw8tw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with editorial changes (mostly to shorten).
