### ISSUE TITLE
[Preety] 2nd scenario visuals

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#184]
**[HIGH PRIORITY]**

1. Don’t show Preety doing “typical reading exercises for first graders.” That is not an accurate way to portray teaching methods for teens or young adults with dyslexia, which are much more specialized than simply reteaching what is regularly taught to very young kids. For example, older kids are more likely to work on more advanced/multisyllabic/academic words, like “stellar.” Consider showing her doing specialized exercises, such as dividing a printed word into syllables (by using a pencil to “scoop” or make a semicircle under each syllable) or moving around square letter tiles on a magnetic board, with the consonant tiles all in one color and the vowel tiles all in another color (to help kids with dyslexia focus on the vowel sounds).

2. Instead of showing Preety's handwriting, consider showing her typing and using a spellcheck where nearly every word has red underlining to indicate there is a problem.

3. Consider showing her doing maths or some other advanced subject to help underscore that her struggles with reading are not due to a lack of intelligence.

In case helpful, here is COGA's consolidated feedback on the Preety script with tracked changes:
https://docs.google.com/document/d/17nVmc7-9Whv0jtwVWNaX_svGC-asP9YBrU_BsfxnN80/edit?usp=sharing

**Comment by nitedog** [comment]
1. Changed the exercise, as suggested, to specialized homework (as described).
2. Seems to contradict (1) above; moved showing Preety typing to scenario 6.
3. The focus here is on reading, showing math in the visuals seems confusing.
