### ISSUE TITLE
[Martine] connections between scenes and a couple of other bits

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#19]
I really like the flow of information and how it's been edited into this new version. 

Just a couple of bits: 

To help it connect with 2, at the beginning of 3, suggest inserting 'Because it's online...' 

Same for at the beginning of 4, suggest adding/editing to 'If I can't do this, I need to spend a lot of time finding a workaround.' 

In 7, there's somethign bugging me about they're too inaccurate 'for me', suggesting it's more of a personal issue. Suggest 'some videos have automatic captioning but it's still generally inaccurate...'

In 8, suggest 'Even though I can't rely on it fully, I might also lip read...' because I think the way it's written now still suggests that lip reading is a reliable option. 

In 9, I think there's a small something needed there to make the connection between the different modalities of language. 'I'm so used to signing as my first language and it's very different, because of this, it's hard for me to follow courses...'

**Comment by nitedog** [comment]
Addressed in latest revision.
