### ISSUE TITLE
Global suggestion for last sentence in EO's "How People With Disabilities Use the Web" video series

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#193]
**[LOW PRIORITY]**
COGA suggests using “me” or “people like me” in the tagline in all of these videos. We think the tagline will be more compelling if it is more personal.

**COGA's suggested rewording:**
All this has one thing in common: your design can include [ADD: me] or exclude [DELETE: people] [ADD: me].

**Comment by nitedog** [comment]
See also issue #55

**Comment by nitedog** [comment]
Closing this duplicate issue, which EO is still working on in #55.
