### ISSUE TITLE
Consider making at least one of the nine personas non-binary

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#194]
Please consider making at least one of the nine personas non-binary in "How People with Disabilities Use the Web."

**Comment by julierawe** [comment]
No COGA-specific aspects here. 

EO's set of nine personas already covers a range of ages and ethnicities. We simply wanted to raise gender with you as one more way of being inclusive.

**Comment by nitedog** [comment]
Thanks for clarifying!

**Comment by iadawn** [comment]
This idea was introduced and [discussed at EO in December 2021](https://www.w3.org/2021/12/17-eo-minutes). The discussion identified that using non-binary pronouns and references wasn't possible in some languages as there is no agreed forms to refer to non-binary people. The feeling was that while inclusion is good doing so in this case would undermine the key goal of bringing accessibility content to an international audience.
