### ISSUE TITLE
[Yun] 3rd scenario: Consider adding trouble seeing light-gray text

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#195]
**[MEDIUM PRIORITY]**
In addition to trouble seeing small text, consider adding a sentence about Yun having trouble seeing light-gray text or other light-colored text.

**COGA's suggested rewording for 3rd scenario audio:**
My trouble is all this small text on different websites! Why do they write so small? I know how to make the text size bigger but it doesn’t work with all websites. [ADD: And sometimes the text is light gray and is very hard to see.] Sometimes everything seems to break down – the text overlaps or goes somewhere else or disappears completely. Or, I have to scroll sideways to read – I don’t have time and energy for that [chuckles].

In case helpful, here is COGA's consolidated feedback on the Yun script with tracked changes:
https://docs.google.com/document/d/1XQaPkwJMjkhveFYGZ9deYuqTmU0xH8lFm5_03-DeKd8/edit?usp=sharing

**Comment by nitedog** [comment]
Can you say more about your rationale for this suggestion?

**Comment by julierawe** [comment]
This is not a cognitive issue. We are suggesting EO expand beyond small text to include another common issue with low vision.

Contrast sensitivity is one of five types of visual impairments listed in the overview in W3C’s 2021 editor’s draft of “Accessibility Requirements for People with Low Vision.” [Section 2.4.3 ](https://w3c.github.io/low-vision-a11y-tf/requirements.html#contrast-sensitivity)defines contrast sensitivity as “the ability to detect differences in brightness, for example, to discern text from its background. A common accessibility barrier for people with low contrast sensitivity is gray text on a light background.”

Contrast sensitivity is specifically tied to aging in [Understanding Success Criterion 1.4.3: Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html): "The 4.5:1 ratio is used in this provision to account for the loss in contrast that results from moderately low visual acuity, congenital or acquired color deficiencies, or the "loss of contrast sensitivity that typically accompanies aging."

In case helpful, here are all of COGA's responses to EO's follow-up questions:
https://docs.google.com/document/d/1m1piIXXGPtQeRNjYpch3MMgFP1uy3GBA0XbgLUqw8tw/edit?usp=sharing

**Comment by nitedog** [comment]
The suggestion to address the low vision issue of light-gray on white was addressed in the Visual script (issue #283) because this script is already very full and dense.
