### ISSUE TITLE
[Yun] 6th scenario: Consider adding reluctance to use new sites, fear of scams, and frustration when can't find things

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#198]
**[MEDIUM PRIORITY]**
1. Given Yun’s advanced age and trouble using other websites, consider making him reluctant to switch to a new way of shopping for groceries. We suggest he makes the switch because a recent fall makes it hard for him to walk to the store like he usually does.

2. Consider adding that Yun is uncertain about using a new site and only feels confident if his daughter tells him it’s safe/not a scam.

3. Consider adding that not all grocery items are easy for Yun to find. This is a common problem, especially for users who may be overwhelmed by lengthy search results and/or have less patience with clunky navigation systems. 

**COGA's suggested rewording for 6th scenario:**
[DELETE: "But sometimes websites work well!] Our grocery store now has an online shop, [DELETE: which is fantastic — I don’t have to carry all the shopping anymore [chuckles].] [ADD: which is helpful because I fell recently and can’t walk far. My daughter says the site is safe for me to use. I get many emails and phone calls from scam artists so I like to check with my daughter first before I do anything new on the computer.] The [ADD: grocery store’s] text is big and it has big links and buttons. It just seems clearer and easier to find things – everything is where it should be on every page. I can also store my address and credit card numbers because I have difficulty remembering them. But somehow the computer remembers my information for this website anyway – all I have to do is select the address or credit card numbers without typing them each time. [ADD: But I often do not buy everything I need because I can not find them. Where they put things just doesn't make sense to me. If I could get everything I need, I would only shop here.] I wish all websites could be that easy."

In case helpful, here is COGA's consolidated feedback on the Yun script with tracked changes:
https://docs.google.com/document/d/1XQaPkwJMjkhveFYGZ9deYuqTmU0xH8lFm5_03-DeKd8/edit?usp=sharing

**Comment by nitedog** [comment]
Some of these suggestions seem to contradict previous comments we received on stereotypes for older people. Can you say more about the COGA-specific rationale for your suggestions?

**Comment by nitedog** [comment]
The focus of this scenario was adjusted more specifically to describe the impacts of memory loss (#196 & #197).
