### ISSUE TITLE
[Ian] Global concern about Ian's gender and race/ethnicity

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#199]
**[HIGH PRIORITY]**
COGA highly recommends making this autistic persona not male and not white. Why? The white middle-class male autistic stereotype actively harms other individuals who are autistic because it leads to underdiagnosis. 

This request to change Ian's gender to female or non-binary and ideally also to make this a person of color can be accommodated without rewriting who Ian is at their core, though a name change may be needed.

Also, it would be great if this character could be portrayed by someone with lived experience because they are likely to bring a passion to it that only an autist can.

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
We will consider the ethnicity and visual appearance of the person during the casting, there is no limitation to white male-looking.
