### ISSUE TITLE
[Ian] Global concern about Ian's job

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#200]
**[HIGH PRIORITY]**
Please change Ian’s job to a more senior-level position than “data entry clerk” to avoid stereotyping about/setting low expectations for people with autism. COGA suggests making Ian a "data scientist."

Similarly, please remove "part-time" from Ian's text-only user story. (The video script does not mention "part-time," but for the reason mentioned above, COGA feels strongly that "part-time" in the text-only user story adds to negative stereotyping about autistic people.)

To put Ian in perspective, look at EO's nine personas for "How People with Disabilities Use the Web" and compare Ian's part-time entry-level job to the employment status of the other eight personas. With the exception of Luis (whose script says he is seeking full-time work) and the three students (whose employment statuses are not mentioned), all the other personas are portrayed as having highly regarded occupations:
1. Yun: Retired professor with low vision, hand tremors, and short-term memory loss
2. Ilya: Senior-level accountant who is blind
3. Alan: Quadriplegic reporter with no mention of whether he works part- or full-time
4. Lee: Color-blind person with unspecified occupation that involves drafting documents and interpreting bar charts — no mention of whether he works part- or full-time
5. Luis: Person with Down syndrome who works part-time but is seeking a full-time job
6. Martine: Student
7. Noor: Student
8. Preety: Student

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Changed job to "data scientist" as suggested.
