### ISSUE TITLE
[Ian] 2nd scenario visuals showing Ian greeting colleagues

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#201]
**[HIGH PRIORITY]**
Consider the office visuals carefully so that this video doesn't fall into a "Rainman" trope. 

Autists do like people, but may have a different way of interacting. Small talk and small greets can be unlikely or uncomfortable. But real tactical connections, such as bringing a meaningful gift to someone because you know it will make a difference for them, are more characteristic.

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Adjusted visuals and added note.
