### ISSUE TITLE
[Ian] 3rd scenario about Ian adjusting to change

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#202]
**[HIGH PRIORITY]**
1. Avoid suggesting that Ian struggles to adjust to any type of change. Specify that he is struggling to adjust to changes that involve losing the ability to use/control the technology. Emphasize how time pressure adds to the stress. (COGA suggests having Ian log into a morning teleconference meeting and needing to instantly adjust to changes in the teleconference controls that were pushed out overnight.)

2. Don't show Ian's colleague telling him what to do. The onus should be on technology makers to help users know what to do.

3. In addition to showing Ian's frustration, consider showing him making a joke to help humanize him and to help challenge stereotypes about autistic people.

4. If there's time for this video to include a possible solution, have Ian mention that he rolls back to a previous version when he can't get the new version to work.

**COGA's suggested rewording for 3rd scenario audio:**
"Except when something changes. [DELETE: Sometimes it’s just a new version of the computer program I use. It’s confusing if I’m not prepared for changes in how things usually work. Our administrator usually shows me the changes before an update is installed on my computer to avoid surprises.] [ADD: and I don’t have enough time to figure out how to use the new version, like when I find out my teleconference app has changed some important controls when I’m trying to log in for a meeting. It’s very stressful if I can’t join and I worry about getting reprimanded for being late to the meeting. Sometimes I press the wrong thing and everything just changes and I do not know how to go back. It makes me feel like I just cannot cope. I am trying to work, but I just can’t and I start to panic, and then I can't even talk anymore. Sometimes I think the people who make our company intranet must hate me. (Only joking.) Sometimes I can roll back to a previous version if I can’t get the new version to work for me. That saves me."

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes. Split this into two scenes, one about warning before updating/changing and the second about roll-back/undo.
