### ISSUE TITLE
[Ian] 4th scenario about Ian reacting to error message

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#203]
**[HIGH PRIORITY]**
1. Replace current error message that clearly identifies the problem ("DATETIME FORMAT INCORRECT") with unclear error message that only uses the words “system error.” Show Ian frustrated by the lack of clarity, not afraid of error messages in general.

2. Replace patronizing wording about “a very scary error message," "Boy!," and "that was some fright."

**COGA's suggested rewording for 4th scenario audio:**
[DELETE: "But once I was also stopped from working because I got this very scary message – it was in red and big capital letters; something about user error such and such. Boy! I thought, what did I do now?! But it was just a small mistake in the date.] [ADD: It’s also really frustrating when I am stopped from work because of an error message that doesn’t tell me what the error is. Error messages that just say “'system error” are so useless.]

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes.
