### ISSUE TITLE
[Ian] 5th scenario audio and visuals about Ian cooking

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#204]
**[MEDIUM PRIORITY]**
1. Consider replacing Ian’s self-doubt with proficiency. COGA suggests making this persona a good cook whose friends like to eat what he cooks. Including friends helps dispel the myth that autists don't like to interact with people.

2. Instead of showing Ian using the navigation system, COGA thinks it is more likely that he would use facets, tags, and search features.

3. For visuals, consider replacing childlike “cooking cloak” with perfect _mise en place_, expertly sliced veggies, etc. Show genuine skill of an autist who really loves something and immerses themselves in it.

**COGA's suggested rewording for 4th scenario:**
"I love to cook when I’m not working. [DELETE: I’m not a good cook yet but I’m learning.] [ADD: My friends love to eat what I cook because I find the best recipes!] Some cooking websites and apps are easy to use —[DELETE: they] [ADD: my favorite recipe sites] list the exact ingredients and have step-by-step instructions. It’s easy to find the recipes [DELETE: in the navigation] [ADD: using the tags] and to [DELETE: understand] [ADD: follow] them."

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes.
