### ISSUE TITLE
[Ian] 6th scenario about Ian reacting to pop-up's and videos on cooking sites

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#205]
**[MEDIUM PRIORITY]**
Make clearer what the barrier is with the pop-up's and the videos that start without Ian pressing play. Allow Ian to explain it. Give him agency.

**COGA's suggested rewording for 6a scenario:**
[DELETE: Other websites and apps are very confusing.] [ADD: Unfortunately, I can’t use some recipe sites even though they have recipes I really want to try.] Especially these where all sorts of videos start playing and pop-up windows appear without me pressing anything. I didn’t ask for this! [DELETE: Why is it giving me all this stuff instead of the recipe?] [ADD: These are overwhelming and aren’t the recipe. All I want is the recipe!]

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes.
