### ISSUE TITLE
[Ian] 6th scenario about Ian reacting to vague phrase "scant cup of brown sugar"

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#206]
**[MEDIUM PRIORITY]**
Make clearer that with an autist like Ian, the language barrier isn’t about understanding the words. He likely has a very large vocabulary. The problem is more likely that he understands the words too well and starts dissecting them until they become meaningless. See suggested rewording based on the experience of an autistic COGA member and that of other autists we know.

**[LOW PRIORITY]**
Consider having Ian speak to the screen in this cooking scene. Let him express his frustration over the use of language directly to the audience.

**COGA's suggested rewording for 6b scenario:**
Or, some [DELETE: use all these confusing] [ADD: sites use meaningless] words and phrases [ADD: and don’t even bother explaining them.] I mean, [DELETE: I had to ask a friend] what [ADD: is] “a scant cup of brown sugar” [delete: means.] [ADD: “Scant” could mean so many different things!!! Instead of “scant,” just say what you mean,] [DELETE: “Why don’t they just somewhere say that a scant is] a cooking cup filled just below the top” [ADD: or “not quite a full cup”]? That would be easier to understand for everyone.

In case helpful, here is COGA's consolidated feedback on the Ian script with tracked changes:
https://docs.google.com/document/d/1zDinqPxwUdG60POmZ2vBkb0L02RpfgnMRKIQQG5k3jw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes.
