### ISSUE TITLE
[Luis] Global concern about Luis's job

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#207]
**[HIGH PRIORITY]**
Avoid infantilizing Luis by making clear at the very beginning of the video that he is an employed adult. (Some COGA reviewers thought he was a child until they got to the 6th scenario, which is the first time he mentions he has a job.)

If EO has time to make more substantial changes to Luis’s story, COGA thinks it would be ideal to connect his job to his passion for basketball. COGA has drafted a version where he works at a stadium and is portrayed as an asset to the professional basketball team. See link below.

**Minimum suggested change to get Luis's job in 1st scenario:**
"Hello, I am Luis. I have Down syndrome. [ADD: I like my job at the library and] I love basketball..."

**Alternative suggested job and other changes to give Luis a more positive story arc:** 
See 4th column in COGA's consolidated feedback on the Luis script:
https://docs.google.com/document/d/1VzYUBM192J_pvuEcHAsdIywh7xngcbFYR2IaWhiQCLk/edit?usp=sharing

**Comment by nitedog** [comment]
Can you say more about which parts seemed to infantilize Luis?

**Comment by bakkenb** [comment]
I am okay with the idea of mentioning the job in sequence 1, but I don't know if it is absolutely needed. 

I see the comment is about  the perspective of Luis seeming to be infantilized. My perspective of the current sequence 1 is that he is at least 18 or older because it states that he "played on my school team" and now chronologically after that he has joined a club. In my opinion that explains that he is at least a young adult.

**Comment by julierawe** [comment]
Hi, here is COGA's response to your follow-up question about which parts infantilize Luis:

**1. Not clear Luis has finished school:** Luis says he "played on [his] school team" and now he plays on a club team. But it's not clear from the script that he finished school. For example, he could have played on a school team in 6th grade, and now he's in 10th grade. It's often hard to tell based on looks alone if someone is a teenager or a young adult.

**2. Use of incorrect grammar:** Some turns of phrases may inadvertently infantilize Luis, like “it suddenly looks all different” in the 4th scenario. If you remove “all,” then the grammar is OK. Please use simple but correct sentence structure for Luis.

**3. Minimizing Luis's employment:** The persona does not emphasize the strengths and value of Luis. His job isn't mentioned until the last scenario. And with a part-time job sorting books in a library, it sounds like he will have very little income or income potential, which crosses him off the list for many target audiences. 

**4. Title of Luis's user story:** Consider editing the title, which refers to him as a "basketball fan" rather than a fully fleshed adult/member of his community. Most of the other personas in this series refer to the person's occupation.

In case helpful, here are all of COGA's responses to EO's follow-up questions:
https://docs.google.com/document/d/1m1piIXXGPtQeRNjYpch3MMgFP1uy3GBA0XbgLUqw8tw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes.
