### ISSUE TITLE
[Luis] Global comments about Luis's speech and reading

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#209]
**[MEDIUM PRIORITY]**

1. Re Luis reading "more slowly": Reading slowly is not directly associated with Down syndrome. If EO thinks it is essential to mention that Luis reads slowly, COGA asks that you put some distance between  Luis saying that he has Down syndrome and him saying that he reads slowly. You could move this reading detail to the beginning of 3rd scenario so it’s more of an individual characteristic and not directly tied to Down syndrome: "Sometimes, I take longer to read things, but this app is really easy to use..."

2. Re Luis speaking "more slowly": Is it essential in the 1st scenario for Luis to comment on his speech? The script never comes back to this, so COGA recommends removing this sentence altogether: "I read and speak more slowly like that." If for some reason EO thinks it's essential for Luis to comment on his speech, we recommend replacing “I speak more slowly” with a broader statement that covers other distinctive aspects of his dysarthria, such as articulation and stuttering:  "My speech sounds different than most people, and it can be harder to understand sometimes."

3. Avoid scripting contractions for Luis such as “I’m” and “I’d” because pople with Down syndrome are unlikely to use contractions.

4. Avoid scripting difficult words like “difficult.” For example, Luis is more likely to say “hard” than “difficult.”

**COGA's suggested rewording for 1st scenario** (which includes mentioning his job, per Github issue #207):
"Hello! [DELETE: I'm] [ADD: I am] Luis. I have Down Syndrome. [DELETE: I read and speak more slowly like that.][Listeners might notice that Luis is speaking with some difficulty.] [ADD: I like my job at the library and] I love basketball! I played on my school team and am now playing in a club." 

In case helpful, here is COGA's consolidated feedback on the Luis script with tracked changes:
https://docs.google.com/document/d/1VzYUBM192J_pvuEcHAsdIywh7xngcbFYR2IaWhiQCLk/edit?usp=sharing

**Comment by nitedog** [comment]
How can we better describe some of the implications of Down Syndrome, to help people better understand it?

**Comment by bakkenb** [comment]
I agree with the recommendations set forth by Julie (COGA group). They are helping with accuracy of what most likely would be communicated and how it would be communicated. 

I also agree with Shadi asking the question, what can we do to add even more implications of this user story with access issues to digital content, tools, and systems. 

This is great feedback!

**Comment by julierawe** [comment]
If you want Luis to describe the challenges that come with Down syndrome, here is our suggestion:

> “I have an extra chromosome. This changed how my body grew. As a kid, it took me longer to learn things like how to talk and how to read and write. I am a hard worker, but sometimes I need more time than other people. It helps me when people use words I know and pictures and symbols.”

Alternatively, Luis could talk about being treated differently because of how he speaks and learns rather than trying to jam a comprehensive description of Down syndrome into his introduction. A COGA member did a study in 2016 with people with intellectual disabilities more broadly that found that people identify disability through physical markers (“looking different”), receiving help from people like staff, and communicating in different ways – although the people in the study often pointed to others who had disabilities rather than themselves. Overwhelmingly, descriptions of a person’s own disability were related to others judging them or treating them poorly, rather than descriptions of functional limitations.

Also, here are several patterns you could add that would help Luis access digital content, tools, and systems:

- [**Separate each instruction:**](https://www.w3.org/TR/coga-usable/#separate-each-instruction-pattern) When instructions are all blended into a single paragraph, it can be difficult for Luis to task plan and follow steps.

- **Directional clarity:** Instead of the words “left,” “right,” “up,” “down,” use graphics and other ways to help Luis know where to click or how to swipe.

- **Slowing down or providing control over timed experiences** in order to be able to extend time allowed. For example, when discussing the ticketing app in the 4th scenario, rather than only focusing on understandability (repeated from the 3rd scenario), perhaps add something about timed forms that are common when buying things online. Perhaps Luis goes to put in his information to purchase tickets, but the app only gives him 10 minutes before timing out and it’s not enough time to input his name, address, credit card number, etc. (That aligns with his statement in part 3: “Sometimes, I take longer to read things.”) This also provides an example that doesn’t just suggest that Luis can’t understand, but rather that he just needs more time to understand.

- **Using precise language:** For example, “the game starts in half an hour” is vague, while “the game starts at 2:30 is concrete… even better if that comes with some kind of visualization of what that is in time, like a line on a calendar.

- **Support and UI instructions are provided just in time** rather than at the beginning long before they are needed.

In case helpful, here are all of COGA's responses to EO's follow-up questions:
https://docs.google.com/document/d/1m1piIXXGPtQeRNjYpch3MMgFP1uy3GBA0XbgLUqw8tw/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated the essence of this issue.
