### ISSUE TITLE
[Luis] 2nd scenario: Consider replacing jargon with more conversational language

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#210]
**[MEDIUM PRIORITY]**
Consider removing or replacing “chat function” because its sounds jargony/not conversational. Likewise, consider replacing "exchange" with simpler wording, like "send." 

**COGA's suggested rewording for 2nd scenario:**
We use an app for our team. It has a calendar with all our practices and games. I can record my results, [DELETE: and there is a chat function too.] I can chat with the coach and with my teammates, and [DELETE: we exchange] [ADD: We use the app to send] photos and jokes and so [chuckles].

In case helpful, here is COGA's consolidated feedback on the Luis script with tracked changes:
https://docs.google.com/document/d/1VzYUBM192J_pvuEcHAsdIywh7xngcbFYR2IaWhiQCLk/edit?usp=sharing

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes.
