### ISSUE TITLE
[physical] Sequence 4 Audio - Sentence structure needs to be simplified

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#214]
[medium-high]
I understand the content of this sequence but I had to read it slowly at first to follow. Suggest we try and simplify how this is written/spoken.

Also fixing a typo in the word "ergonomic."

Current:

> Some people use both – specialized keyboards, for example keyboards with larger keys, more space between the keys, or in many different ergnomic designs, or pointing devices, for example joystick with enlarged lever – so that websites and apps need to support concurrent input devices.

Suggestion:

> Some people use both specialized keyboards and pointing devices. For example keyboards with larger keys, more space between the keys, or a different ergonomic design; or pointing devices like a joystick with an enlarged lever. So websites and apps need to support concurrent input devices.

**Comment by nitedog** [comment]
Changed as suggested.
