### ISSUE TITLE
[speech] Sequence 5 Audio - Small rewrite for clarity and flow

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#215]
[medium-high]
Trying to fix some small issue with flow and also clarify this sequence.

Current:
> Websites or applications that require speech input can a barrier for some people; for example, when online applications such as customer support systems rely on automatic speech recognition without providing an alternative way for communication.

Suggested: 
> **_Some_** websites or applications that require speech input can **_be_** a barrier for some people; for example, when **_an_** online **_application_** such as **_a_** customer support systems relies on automatic speech recognition without providing an alternative way for **_a user to provide input_**.

**Comment by nitedog** [comment]
Reworded entirely, also to address #238.
