### ISSUE TITLE
[speech] Sequence 6 Audio - Do we need more issue definition here?

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#216]
Current wording: 
> Other situations that can be problematic with automatic speech recognition functionality are when people use assistive devices to generate speech. Examples are using “speech generated by a computer” [speech synthesis coming from a computer, sounding like that of Stephen Hawking] or devices like an electrolarynx, which “converts vibrations on the throat to sound” [speech coming from an electrolarynx device].

This sequence starts off with "Other situations that can be problematic..." and then tells of two types of speech recognition. But there is no explanation or phrasing that states why they can be problematic. Is this okay? Are we just trying to provide other types of speech recognition here, or are we trying to say what other problems can occur. If that latter, then I think we need more definition of the issues here.

**Comment by MicheleAWilliams-A11y** [comment]
+1 - I didn't understand this paragraph at all; seemed to be missing something. I'll make a suggestion on my Google Doc based on what's in the current resource.

**Comment by nitedog** [comment]
Reworded to also address #238.
