### ISSUE TITLE
[visual] Sequence 5 Audio - Reverse order presented

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#218]
[medium-high]
Harder to follow quickly unless the order material is presented in is reversed. See below for suggestion.

Current:
> Websites and apps also need to be programmed and designed to adapt to different text sizes and line spacing without the text overlapping, getting cropped, or creating difficult scrolling. For example, other people with low vision do not use any assistive technology. They increase the text size or adjust other properties of the text, such as the font type and line spacing.

Suggested: 
> **_Some_** people with low vision do not use any assistive technology **_to meet their visual needs_**. **_Instead_**, they increase the text size or adjust other properties of the text, such as the font type and line spacing. **_Therefore_**, websites and apps also need to be **_designed and programmed_** to adapt to different text sizes and line spacing without the text overlapping, getting cropped, or creating difficult scrolling.

**Comment by nitedog** [comment]
Reworded entirely, also to address #239.
