### ISSUE TITLE
[Perception] Sequence 1 Audio - Wording changes

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#220]
[High]
Wording change for clarity and to flow into next sequence...

Current: 
> When content is designed right, people perceive it through different senses depending on their needs and preferences. For example, some people are not seeing the screen or hearing the audio.

Suggested:
> When content is designed right, people **_can_** perceive it through different senses depending on their needs and preferences. For example, some people **_do not see_** the screen or **_hear_** the audio.

**Comment by nitedog** [comment]
Changed as suggested.
