### ISSUE TITLE
[Perception] Sequence 2 Audio - Wording Edits

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#221]
[Medium-High]

I would delete the "For example," at the beginning of this sequence. it is not needed.

And one additional wording edit below.

Current:
>For example, people who are blind or who have low vision often rely on hearing or on touch rather than sight. For video, content authors need to ensure that the visual information is provided in audio too. Often these descriptions of visual information use existing pauses in the audio track, or the audio is created from the start with sufficient description of the scenes, characters, and other visual information in the video. [brief pause to listen to a short slice of audio description while the video is being shown in the visuals]

Suggested:
>People who are blind or who have low vision often rely on hearing or on touch rather than sight. For video, content authors need to ensure that the visual information is provided in audio too. Often these descriptions of visual information **_are placed in_** existing pauses in the audio track, or the audio is created from the start with sufficient description of the scenes, characters, and other visual information in the video. [brief pause to listen to a short slice of audio description while the video is being shown in the visuals]

**Comment by nitedog** [comment]
Changed as suggested.
