### ISSUE TITLE
[Perception] Sequence 5 Audio - Very small wording tweaks

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#223]
[ED - Medium]

Just some small edits I believe are needed.

Current: 
>Similarly to people who are blind, people who are Deaf and Hard of Hearing use haptic senses too; for example, through vibrations alerts on the mobile phone instead of auditory notifications.

Suggested:
>Similarly to people who are blind, people who are Deaf and Hard of Hearing use haptic senses too; for example, through **_vibration_** alerts on **_a_** mobile phone instead of auditory notifications.

**Comment by nitedog** [comment]
Changed as suggested.
