### ISSUE TITLE
[Input] Sequence 4 Audio - More clarity in sentence transition

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#224]
[medium-high]
I feel that this sequence is explaining two separate issues for cognitive and LD and needs a little better transition in the middle to clarify these are two separate things to be aware of. 

Current:
>People with cognitive and learning disabilities often also need more time for typing, writing, and clicking on websites and apps. Websites and apps also need to provide clear instructions and options to find and correct mistakes in their input, to help people complete forms and processes effectively.

Suggestion:
>People with cognitive and learning disabilities often also need more time for typing, writing, and clicking on websites and apps. **_In addition_**, websites and apps **_should_** also provide clear instructions and options to find and correct mistakes in their input, to help people complete forms and processes effectively.

**Comment by nitedog** [comment]
Changed as suggested.
