### ISSUE TITLE
[Navigation] Sequence 6 Audio - Reword first sentence

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#226]
[high]
I feel the first sentence in this sequence needs a small tweak to tie in previous sequence and read better. Suggestion below:

Current:
>As do people with physical disabilities who are using different types of specialized keyboards and pointing devices – they also rely on websites and apps that help them identify and correct mistakes, such as accidental typing and clicking. 

Suggested:
>People with physical disabilities who are using different types of specialized keyboards and pointing devices also rely on websites and apps that help them identify and correct mistakes, such as accidental typing and clicking.

**Comment by nitedog** [comment]
Changed as suggested.
