### ISSUE TITLE
[Martine] Captioning references are vague

### ISSUE THREAD

**Issue by JEGrisham** [w3c/wai-people-use-web-videos#227]
In Seq 3 - "Some lectures have realtime captioning by real humans." 

I feel that “real humans” is not a typical or realistic statement one might say/hear. I would suggest this be “real people, “Human captioners,” or even “people who do the captioning.”

The information about closed captions is not entirely accurate. My concern is that how this is phrased might appear that closed captions are different from automatic captions. They are not…it’s the delivery of the captions that differ -- closed vs. open -- and both of these can be done using automatic captions or human-driven captions. In other words, automatic captions can be open or closed captions just like human captions can be open or closed. Not sure you want to go down the rabbit hole of closed and open captions on this because it requires a bit more information and it's not something a Deaf person. 

The reference of concern is: "For our assigned videos, however, I rely on closed captions. These are edited so that they are not too long and are properly synchronized with the audio." 

I feel these sentences should be edited slightly so that it’s clear that it’s still human captioning or touched by humans. I would recommend doing something like this – “For our assigned videos, however, I rely on captions that have been reviewed and edited prior to being put on the videos. When they are edited, they are not too long and are properly synchronized with the audio.”

**Comment by nitedog** [comment]
References to open/closed captions has been removed. This sequence now reads as follows:

> Some lectures have realtime captioning typed by human captioners. This is more accurate than automatic captions, which often don’t recognize specialized terms in the lectures. For our assigned videos, I rely on good captions. These are edited so that each sentence appearing on the screen is not too long and is synchronized with the audio. I also often find myself needing to adjust the text size and colors of the captions, to be able to read them better. Some apps also allow me to move the captions to the top or bottom of the video, so that they are not in the way.
