### ISSUE TITLE
[Auditory] Recommended edits for clarity/accuracy

### ISSUE THREAD

**Issue by JEGrisham** [w3c/wai-people-use-web-videos#228]
This script looks really good and I just have some recommendations around edits for clarity as well as accuracy. 

Seq 1 – there is a tense typo.  "Auditory disabilities include..."  - remove the s is includes. 

Seq 4 – I feel it contradicts info presented in the Martine script. 
"While automatic captions are gradually improving, they are currently too inaccurate for reliable use. For example, they don’t recognize specialized terms and names, people speaking in videos are not identified, and the sentences can sometimes run together making it hard to keep up."

I would suggest this rewrite: 

While automatic captions are gradually improving, many automatic caption programs are not reliable. For example, the captions that are generated do not recognize specialized terms and names, speech variations, people speaking in videos are not identified, and the sentences can sometimes run together making it hard to keep up.

Seq 5 - "with and without hearing aids." 
I would change to “with or without hearing assistance.” Hearing aids are specific hearing assistance device and "hearing assistance" is generic. 

Seq 6 - "Sign language has a different grammar and vocabulary than spoken and written language, so some people might not be as fluent in reading and writing depending on the schooling they received."
 
Suggest replacing “schooling” with “training” – it’s not necessarily school that has an impact, it can be speech therapy, training classes, etc. 

Seq 7 - Recommend deaf-blind to DeafBlind. This is the way the DeafBlind community writes this label per a friend of mine who is DeafBlind. Other scripts show deafblind.  DeafBlind or deafblind are both correct...I just shared what a friend in that community shared with me.

**Comment by nitedog** [comment]
- Seq 1: reworded entirely
- Seq 4: reworded, also considering #173 and #227 
- Seq 5: reworded and changed to "hearing device"
- Seq 6: reworded entirely
- Seq 7: will be addressed by #233
