### ISSUE TITLE
[Auditory] Lots of updates and comments

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#229]
I find it easier to process my comments in a Google Doc. (Notably, that's what kept me from commenting before.) Thus, for now I'm uploading this Doc and when I have a chance I'll translate them into tickets.

https://docs.google.com/document/d/1cnp1Z1p4A3LwGouc_AZleTyHAMZuYgHqEsGzZq6wZ_8/edit?usp=sharing

**Comment by nitedog** [comment]
Revised to incorporate the essence of these excellent suggestions.
