### ISSUE TITLE
[Cognitive] Comments and revisions throughout

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#230]
Like with Auditory, here's a Google Doc that synthesizes my comments and I'll repost to GitHub as needed.

https://docs.google.com/document/d/1zahP6_AGzZh5W3HPIuadbnfj8n8nOuCEOHWs7JU_yOw/edit?usp=sharing

**Comment by nitedog** [comment]
Revised to incorporate the essence of these excellent suggestions.
