### ISSUE TITLE
[Perception] Scene 1, small edit

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#235]
When content is designed right, people perceive it through different senses depending on their needs and preferences. For example, some people are not seeing the screen or hearing the audio. 

Suggest: 
When content is designed correclty, people can perceive it through different senses depending on their needs and preferences. People who can't hear audio can read it instead, or people who can't see the screen can listen to it. 
(It doesn't have to be changed exactly to that, but the -ing form  of the verbs need changing from the original.) 

Or, on second thoughts, just get rid of that second sentence maybe? It's covered in scene 2 and would save some space.

**Comment by nitedog** [comment]
Reworded, also to address #220.
