### ISSUE TITLE
[Diverse Abilities - Global] Suggest remove "differently"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#237]
Throughout the scripts the opener references the spectrum of that group as in 'some, none, or different'. For instance, "Visual disabilities includes people who have low vision, do not see, or see differently."

Saying "differently" is not descriptive and often the script doesn't expand on these differences (such as with visual disabilities, expanding on something like tunnel vision or blurred vision). It's also leaning towards "differently abled" type language that many people don't subscribe to.

Wonder if there's a different way to describe that some people have partial but altered perceptions.

**Comment by nwhysel** [comment]
Color blindness or similar/related divergences from 20/20 vision.

**Comment by nitedog** [comment]
Addressed through various updates to each script.
