### ISSUE TITLE
[Speech] Various updates and comments

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#238]
A few wording options for Speech, plus an attempt to address issue #216 

https://docs.google.com/document/d/1s-6UnAHnU84Hx3v_MQRljd_Ua-XMIbfPPOoCvs5UDMI/edit?usp=sharing

**Comment by nitedog** [comment]
Revised to incorporate the essence of these excellent suggestions.
