### ISSUE TITLE
[Cognitive] Change positioning of "intelligence"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#240]
In the updated wording, we shouldn't position "intelligence" in this way:

> Cognitive and learning disabilities affect how people process and remember information. It is an umbrella term for a broad range of differences and disabilities, and many of them do not affect overall intelligence.
> [Next scene] For example..._[dyslexia content]_

This makes it seem like disabilities that do impact intelligence are a bad thing. 

Suggestion: 
> "Cognitive and learning disabilities refers to a broad range of differences and disabilities that affect how people process and remember information." 

If we need it, maybe later in the script we can fit in something about "misperceptions" or "misconceptions" about what these differences mean, but it may be worth just leaving it out as well.

**Comment by nitedog** [comment]
Keeping this wording to address feedback from COGA TF in issue #261.
