### ISSUE TITLE
[Speech] grammer

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-people-use-web-videos#247]
Seg 1 Audio:

Speech disabilities affect how people **speaking**, including not speaking and speaking in a range of different ways, such as patterns, pitches, and sounds.

should be:

Speech disabilities affect how people **speak**, including not speaking and speaking in a range of different ways, such as patterns, pitches, and sounds.

**Comment by nitedog** [comment]
Also caught by @brianelton

**Comment by nitedog** [comment]
Fixed typo (by way of #257).
