### ISSUE TITLE
[Perception] misspelling

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-people-use-web-videos#248]
For example, some people do not see the screen or hear the audio, and rely on websites and apps that can **preent** the information in different ways.

preent should be present

Suggested re-wording:

For example, some people **who** do not see the screen or hear the audio, rely on websites and apps that can present the information in different ways.

added "who" and deleted "and"

**Comment by nitedog** [comment]
Also caught by @brianelton and @kakinney

**Comment by nitedog** [comment]
Fixed typo and made edit as suggested.
