### ISSUE TITLE
[Navigation] phrase confusing - missing word

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-people-use-web-videos#249]
... such as hierarchical menus as well as search functionality; visual orientation cues, such as using background colors to indicate different parts of the content, using unique headings, and placing relevant information in prominent areas; and consistency and predictability of within websites and apps.

 and consistency and predictability **of within** websites and apps.

missing word? could be:

and consistency and predictability of navigation within websites and apps.

**Comment by nitedog** [comment]
Fixed typo.
