### ISSUE TITLE
[Physical] overuse of "For example"

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-people-use-web-videos#251]
There are a lot of "For example" used in this script,  I don't think its needed to lead into the second sequence - and maybe some of the others could be replaced with "such as" or when you have a list of things that fit a category, or "for instance" when referring to the tablet mounted on the wheel chair.

**Comment by jade-mc** [comment]
I can help with editing this out, I've volunteered to do a final proofread/language edit.

**Comment by nitedog** [comment]
Addressed with the rewrite for #273.
