### ISSUE TITLE
[Cognitive] 1st scenario, 1st sentence: Add "understand"

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#252]
[HIGH PRIORITY]
**Add "understand" to the first sentence:** "Cognitive and learning disabilities affect how people process [ADD: , understand,] and remember information."

[MEDIUM PRIORITY]
**Consider splitting up the second sentence and adding the word "cognitive":** "It is an umbrella term for a broad range of [ADD: cognitive] differences and disabilities. [DELETE: and many] Many of them do not affect overall intelligence."

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes (also to address issue #267).
