### ISSUE TITLE
[Cognitive] 2nd scenario (dyslexia): Add more ways to help

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#253]
**[HIGH PRIORITY]**
The current script only mentions adjusting font size, style, colors, and spacing. But these adjustments are more associated with children. COGA wants to make sure the script includes tools and techniques that are used by adults.

Please be sure to add:
- Section headers and white space
- Text-to-speech
- Spelling and grammar tools
- Tools to help remember and fill out information correctly, such as phone number and passwords 

**COGA's suggested rewording:**
For example, many people have varying degrees of dyslexia. Dyslexia affects the ability to recognize and sound out written words, which impacts [DELETE: the] spelling and reading comprehension. [ADD: Using section headers and white space helps people read the content. Grammar and spelling tools, text-to-speech, and] websites and apps that allow adjusting the text size, style, colors, and the spacing between letters, sentences, and paragraphs [ADD: can also] make it easier for people to read the content.  [ADD: They may also use tools that help them fill out forms or remember important information correctly, such as their phone number and passwords. It is important that the page works well with these extensions.]

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with editorial changes (mostly to shorten).
