### ISSUE TITLE
[Cognitive] 3rd scenario (dyscalculia): Need to replace barrier/how to help and also replace Luis for the visual

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#254]
**[HIGH PRIORITY]**

**Replace example of barrier/how to help.** 
- Filling in forms is not a good example of a barrier for people with dyscalculia. The challenges described in the current script are about remembering and writing numbers in the correct order. These are not challenges with understanding mathematical concepts. 
- A more accurate way to remove a barrier for users with dyscalculia is to include alternatives to mathematical abstractions such as a verbal description or visual aids (for things like schedules, temperature, percentages). 

**COGA's suggested rewording:**
Similarly, some people have varying degrees of dyscalculia. Dyscalculia affects the ability to process and work with numbers and mathematical [ADD: concepts] [DELETE: expressions. Websites and apps with options to store and insert long numbers, like credit card, telephone, and social security numbers, make it easier for people to fill out forms.] [ADD: Websites and apps can provide alternatives to mathematical abstractions, such as forms that show a progress bar instead of or in addition to saying “X% completed.” It also helps to have visual aids or text descriptions for things like schedules or temperatures.]

**[HIGH PRIORITY]**

**Replace Luis for the visual.** 
- Luis has Down syndrome. An intellectual disability that affects math is not the same thing as dyscalculia. People with dyscalculia can have very high IQs but struggle with numbers and math concepts.
- If you have to show one of your personas, Preety is more similar and there is often comorbidity between dyslexia and dyscalculia. 
- Instead of showing someone entering a credit card or phone number, it would be better to show a user being confused by a multi-page form that shows “percentage completed” at the top of the page or to show a person looking at a chart or graph.

**[MEDIUM PRIORITY]**

**Replace "mathematical expressions" with "mathematical concepts."**

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes, mainly to keep the current style and tone. Also, swapped the personas between Luis (now in scenario 5) with Preety (now in this scenario 3), to address comment.
