### ISSUE TITLE
[Speech] Suggest reordering of scenes

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#256]
The main suggestion for how to make applications more accessible for people with speech impairments is to allow alternatives. Most of the script, therefore, are highlighting types of speech impairments and some of the barriers that happen when alternatives are not present -- namely if I can't speak at all or if my speech is not one that is recognized by ASR. 

Additionally, it doesn't currently end with the suggestions before going into the tag line. That is, it ends talking about speech that is "not recognized by automatic speech recognition" but then followed by "These are ways to make technology work for me." (That is, we haven't really called out ways to make technology work except a short sentence in the middle.)

Thus, I think we can reorder things a bit to talk about the varying barriers then end on (1) not requiring speech input, (2) not relying on ASR, and (3) providing alternatives. These apply for everyone unlike our other scripts where we had more unique and varied examples per impairment type.

Here's a suggestion of the wording (with a few alterations of the current text, particularly in Scene 5):

> [Scene 1] Speech disabilities affect how people speak _[remainder of current text]_... While it is a common perception among many, speaking differently is not an indication of the person’s intellectual capabilities.
> 
> [Scene 2] For example, some people stutter, pause, or pronounce sounds differently. [brief pause to listen to the protagonist say something like “while you can understand me, speech recognition systems often don’t” (the protagonist has a mild speech disability that most viewers/listeners would understand).]
> 
> [Scene 3] Or, some people do not speak at all because they are Deaf, autistic, have injured or no vocal organs, or because of another condition.
> 
> [Scene 4] To generate speech, “some people use software for generating speech” [we hear that part of the sentence in quotes through speech synthesis coming from a computer] and “some people use hardware for generating speech” [we hear that part of the sentence in quotes through speech synthesis coming from an electrolarynx device].
> 
> [Scene 5] Overall, Websites and apps that require speech input can be a barrier for people with speech impairments, especially when they use automatic speech recognition. Automated systems often have an even harder time understanding speech differences or computer-generated speech. Thus, it's important to provide alternatives that don't require speech. For example, providing customer support not only by phone but additional ways that don't rely on talking like chat or email.
> 
> [Scene 6] [Individual protagonists:] These are ways to make technology work for me. [Narrator:] Accessibility: It’s about people.

**Comment by nitedog** [comment]
Changed order to:

1. Intro
2. People who do not speak
3. People with different speech patterns
4. People who use software to generated speech
5. People who use hardware to generate speech
6. Description of barrier and solution for websites & apps
7. Closing
