### ISSUE TITLE
[Speech] Not confident in accuracy of "don't speak because they are"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#258]
This sentence doesn't ring fully accurate/correct to me: 

> "Some people do not speak at all because they are Deaf, autistic, have injured or no vocal organs, or because of another condition."

Being deaf or autistic doesn't always equate to not speaking. Also, "another condition" kind of leaves folks hanging a bit and may not help educate on conditions not often associated with speaking. 

Here's a proposal:

> "Some people do not speak at all which can include people who are deaf, autistic, have injured or no vocal organs, or have other conditions, particularly when they impact one's muscles such as Multiple Sclerosis."

**Comment by nitedog** [comment]
Changed to:

> Some people do not speak at all. This can include people who are Deaf, autistic, have injured or no vocal organs, or have other conditions impacting physical or cognitive speech production.
