### ISSUE TITLE
[Cognitive] 5th scenario (attention)

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#259]
**[HIGH PRIORITY]**

1. **Broaden first sentence** to include more disabilities than just ADHD. It would be especially helpful to mention age-related forgetfulness because it affects so many people. Brain trauma and dementia are other good examples to consider adding.

2. **Reword “affects the impact of distraction”** to be more specific.

3. **Add overlays and auto-playing videos.** 

4. **Consider moving this scenario up higher** because impaired attention affects so many people. 

**COGA's suggested rewording:**
[DELETE: Or, people might have varying degrees of ADHD – attention deficit hyperactivity disorder.] [ADD: Many people have impaired attention, such as people with attention deficit hyperactivity disorder (ADHD), brain trauma, age-related forgetfulness, and dementia.] [DELETE: ADHD affects] [ADD: These cognitive differences affect] the ability to focus [DELETE: for longer periods of time, and it affects the impact of distraction] [ADD: and to resume a task after the user gets distracted.] [DELETE: In addition to] [ADD: It helps to] break up longer passages of text and use headings to organize the content. [DELETE:, websites and apps without.] [ADD: Make it possible to remove] pop-up windows, [ADD: overlays] and automatically playing [ADD: videos and] sounds  [DELETE: also make it easier for people to] [ADD: to help people] focus and follow the content.

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with editorial changes. In particular, broadened this section to "attention" abilities more generally, with list of examples suggested here. Adjusted some of the remaining wording but kept the current style and tone. Also, swapped the personas between Preety (now in scenario 3) with Luis (now in this scenario 5), to address issue #254.
