### ISSUE TITLE
[Cognitive] 6th scenario (learning new designs): Add the word "familiar" 

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#260]
**[HIGH PRIORITY]**
**Add the word "familiar,"** which is distinct from "consistent." The key here is design needs to be familiar as well as consistent. If you consistently use a new pattern that people do not know, you will block many people consistently. 

**COGA's suggested rewording:**
Also, some people experience difficulty orienting themselves in layouts and visual designs that are new to them [DELETE: and with learning the] [ADD: It may also be difficult for them to learn new] keystrokes or gestures needed for interaction. Websites and apps with familiar, consistent and predictable designs and with clear and distinct instructions make it easier for people to orient themselves and complete tasks.

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with minor editorial changes (also to address issue #268). Also, propagated the term "familiar" in scene 2 of the [Navigation script](https://wai-people-use-web-videos.netlify.app/people-use-web/videos/tools/navigation).
