### ISSUE TITLE
[Perception] 7th scenario (Converting text into symbols): Is this about reading disabilities? Or adaptation tools like AAC?

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#261]
**[HIGH PRIORITY]**
This scenario seems to be mixing together two very different things. We can't tell if you are talking about:

- People with reading disabilities who benefit from web pages that use icons to aid comprehension of the text, OR
- People with speech/language disabilities who use augmentative and alternative communication (AAC) that converts text into symbols.

If this scenario is about "people with reading disabilities [converting] content into formats they can better understand," then:

- Add "using text-to-speech" (as suggested in https://github.com/w3c/wai-people-use-web-videos/issues/253).
- Add "adjusting the font, line spacing, and background color."
- Remove everything that sounds like AAC: "convert text and functionality into symbols. Symbols could be pictures of the words; for example, a picture of an apple instead of the word “apple” (because people with reading disabilities such as dyslexia don't use AAC).
- Consider adding that icons can not only help people understand text, but can help people remember the information too.

If this scenario is about people with speech/language disabilities using adaption tools to show symbols instead of text, then:

- Replace "reading disabilities" with "speech or language disabilities."
- Consider adding cautionary note that until the adapt specification is out, people may be worried because of mistranslation.

**Comment by nitedog** [comment]
Adjusted example to better reflect AAC.
