### ISSUE TITLE
[Presentation] 5th scenario: Avoid confusion about what you mean by "headers"

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#262]
**[HIGH PRIORITY]**

**Be clearer what you mean by "headers"** when describing "less relevant parts of the content" that can be hidden by reading modes.  

- It's OK for reading mode to remove the heading or header at the very top of a webpage (with company logo, social media icons, etc). 
- But it's not OK to remove page titles or section headers, which are extremely relevant parts of the content. 

To avoid this confusion, consider replacing "headers" with "ads" in this sentence: "This includes, for example, web browsers’ “reading modes” that hide less relevant parts of the content, such as sidebars and [DELETE: headers] [ADD: ads.] 

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Replaced "headers" with "front matter".
