### ISSUE TITLE
[Presentation] 6th scenario: Consider adding key terms like kerning, leading, and sans serif

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#263]
[MEDIUM PRIORITY]
Consider adding the key terms that you are already describing in this scenario in case users are specifically searching for these words or phrases:

- Kerning
- Leading
- Sans serif
- Typographic

**COGA's suggested rewording:**
Some reading assistants, for example those that some people with dyslexia might use, can change [ADD: how the text is presented to make it easier to read. This includes changing] the font type, text size, [ADD: and] colors. [DELETE:, and] [ADD: It also includes changing the kerning (] the spacing between letters [ADD:), leading (space between] sentences), and [ADD: the space between] paragraphs [DELETE:, to make text easier to read]. Some people read better with serif-type fonts while others with [ADD: sans] [DELETE: non]-serif fonts. [DELETE: Other] [ADD: Preferences in these typographic] properties [DELETE: of how text is presented] are also highly individual from one person to another, which is why flexible design is so important.

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated most of the suggested edits but not some of the technical terms, to avoid unnecessary complexity.
