### ISSUE TITLE
[Presentation] 7th scenario (glossary): Please show a different persona than Luis

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#264]
**[HIGH PRIORITY]**

Please show a different persona than Luis for this visual. 

As noted in COGA’s feedback on the Luis script https://github.com/w3c/wai-people-use-web-videos/issues/212 :
Users with Down syndrome are unlikely to use glossaries and, if they do, they may have trouble understanding the glossary definitions. A glossary is likely to be very frustrating for Luis. 

Preety may be a better persona to show for this glossary example.

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Adjusted example from glossary to text simplification tools.
