### ISSUE TITLE
[Input] 4th scenario (time-outs and mistakes)

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#265]
[MEDIUM PRIORITY]

1. First sentence: Add "coping" and "task completion" to the list of activities that people with cognitive and learning disabilities need more time for.

2. Add new sentence: "Time-outs should be avoidable when possible."

3. Add new sentence: "Good form design can make mistakes less likely and can support the user through the process of filling out the form."

4. Be more specific in first sentence: "People with cognitive and learning disabilities often need [ADD: a lot] more time..."

**COGA's suggested rewording:**
People with cognitive and learning disabilities often [DELETE: also] need [ADD: a lot] more time for [ADD: coping,] typing, writing, and [ADD: task completion] [DELETE: clicking on websites and apps.] [ADD: Time-outs should be avoidable when possible.] In addition, websites and apps should also provide clear instructions and options to find and correct mistakes in [DELETE: their input] [ADD: inputs such as text fields, so that users can] [DELETE: to help people] complete forms and processes effectively. [ADD: Good form design can make mistakes less likely and support the user through the process of filling out the form.]

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Incorporated much of this wording and concepts with editorial changes.
