### ISSUE TITLE
[Navigation] 2nd scenario

### ISSUE THREAD

**Issue by julierawe** [w3c/wai-people-use-web-videos#266]
**[HIGH PRIORITY]**

1. Add something about memory, which is currently absent from this script and also from all of the other current drafts for “Tools and Techniques” scripts. We suggest: "Findability is especially important for people with memory impairments that make it hard to learn how to use new designs."

2. Add new sentences about orientation: "Orientation also is a key problem. A good site design helps the user know where they are in the site."

3. Add "signposts like breadcrumbs."

4.  For visual, consider replacing Ian with Yun.  

**COGA suggested rewording:** 
Many people with cognitive and learning disabilities rely on clear layout and design to find information on websites and apps. This includes different ways of navigating the content, such as hierarchical menus as well as search functionality; visual orientation cues, such as using background colors to indicate different parts of the content, using unique headings, and placing relevant information in prominent areas; and [ADD: using a consistent and predictable design] [DELETE: consistency and predictability of] within websites and apps. [ADD: Findability is especially important for people with memory impairments that make it hard to learn how to use new designs. Orientation also is a key problem. A good site design helps the user know where they are in the site. This includes different ways of navigating the content, such as hierarchical menus as well as search functionalities. Signposts like breadcrumbs and clear titles also help the user know where they are and what they are doing.] 

In case helpful, here is [all of COGA's consolidated feedback on the latest set of EO scripts](https://docs.google.com/document/d/1WIUsN_iZESQfwCqTUl6w_ukm7oNwTQTCfBZcBIQO7cE/edit#).

**Comment by nitedog** [comment]
Made the first edit as suggested. The remaining addition is too detailed for these videos, which only highlight example issues.
