### ISSUE TITLE
[Cognitive] Scene 6

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#268]
Suggest changing the second half of the scene, 'orient' is used earlier on, and if someone doesn't understand it, then there's a second chance here to make the meaning clear. 

...predictable designs and with clear and distinct instructions make it easier for people to orient themselves and complete tasks.

...predictable designs and with clear and distinct instructions make it easier for people to find out where they are and complete tasks.

**Comment by nitedog** [comment]
Change to "know where they are" (to me, "find out" sounds like a lot of detective work, which it shouldn't be).
