### ISSUE TITLE
[physical] scene 6

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#269]
Because it's a long sentence, suggest: 

Regardless of input modality, websites and apps that provide sufficient time to type and to complete tasks; clear instructions to complete forms and processes effectively; and options to find and correct mistakes in their input, make it easier for people with physical disabilities to interact with them.

to

Regardless of input modality, websites and apps are easier for people with physical disabilities to interact with if they provide sufficient time to type and to complete tasks; clear instructions to complete forms and processes effectively; and options to find and correct mistakes in their input.

**Comment by nitedog** [comment]
Addressed with the rewrite for #273.
