### ISSUE TITLE
[Input] scene 3

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#271]
Mouse needs to be plural (mice? mouses? both always sound rubbish) unless you tweak it from: 

Many people use customized input devices, such as specialized keyboards, mouse, and other pointing devices. 

to

Many people use customized input devices, such as a specialized keyboard, mouse, and other pointing devices.

**Comment by nitedog** [comment]
Revised wording but took suggestion on board.
