### ISSUE TITLE
[Physical] Needs significant rewriting

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#273]
This script seemed to have incomplete sentences/thoughts. Also, the flow of information could use reworking to ensure key points remained together (e.g., pointing out visual focus when talking about keyboard navigation, not later in the script). 

It also started with more diagnosis-type definitions rather than describing the effects/impacts as with other scripts. 

I used Google Docs because that was easier to make suggestions and comments: 
https://docs.google.com/document/d/1UMlnwocsbL8ZSW3YT9Z5GdgWTeueheN1EVakAmuMd6U/edit?usp=sharing

**Comment by nitedog** [comment]
Revised to incorporate the essence of these excellent suggestions.
