### ISSUE TITLE
[All Tools & Techniques] Different opening statement

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#274]
The current opener says, "When content is designed right..."

"Right" doesn't feel like the best word here. Propose instead "with accessibility in mind" or "accessibly" or "inclusively".

**Comment by nitedog** [comment]
@lakeen adds this in [videos survey](https://www.w3.org/2002/09/wbs/35532/HPWD-ABTT-VideoScripts-Thorough/results):

> "When content is designed right," I'm wondering about the word "right" it's seems too vague. How about "inclusively"? - [ED]

**Comment by nitedog** [comment]
Here are some ideas in my order of preference, please add your thoughts:

1. When content is accessible (loses focus on design)
2. When content is designed to be accessible (most accurate but long)
3. When content is designed accessibly (somewhat awkward wording)
4. When content is designed inclusively (loses focus on accessibility)
5. When content is designed with accessibility in mind (seems too long)

**Comment by lakeen** [comment]
+1 for 1. "When content is accessible"

**Comment by jade-mc** [comment]
My vote is for 'when content is designed correctly' for the reasons outlined on the call earlier, but I'm realyl not attached to it.

**Comment by nitedog** [comment]
Kept first option.
