### ISSUE TITLE
[Perception] Proposed changes to the script

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#275]
While I think the script could work as-is, I reworked it a bit: https://docs.google.com/document/d/1sBhj-qNU1yK6DpQnXalTl_7Y3y_bfu8QVEro3IsgGsA/edit?usp=sharing

To summarize why (and I also put this in the comments):
- This described the vision impairments a lot more than those for dead & HOH; propose we be consistent and balanced.
- This doesn't mention deafblind people but seems it should since we talk about Braille devices and haptic feedback (and this also appears in the written version).
- The overall flow now goes from hearing (blind/LV), seeing (deaf, HoH), to feeling (all + DB)
- Within the text certain flows made more sense; for instance, explaining audio descriptions prior to explaining about screen readers was a bit jarring. Video & AD are not what people immediately think of for blind folks so it's needed but I think it needed more ramp up.

**Comment by nitedog** [comment]
There are several excellent suggestions in this re-write, in particular adding deaf-blind more clearly and improving some of the flow. Unfortunately, other suggestions revert previous changes and remove some of the COGA aspects (which are still being refined). I kept the current basic structure but made significant changes on the the middle sections to (1) cut back on repetition with other videos and (2) add deaf-blind.
