### ISSUE TITLE
[Presentation] Update examples in Scene 1

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#276]
Since this script is about vision, hearing, and cognition, this should be better reflected in the opening scene if giving examples. The current text only mentions the first 2:

> For example, some people do not see well and need to adjust how websites and apps appear, or they do not hear well and need to adjust the audio.

I recommend either leaving this out or fully explaining the examples to set the right tone for the content. For instance:

> When content is designed right, people can adjust its presentation to make it easier to distinguish and understand. This could include adjusting screen size and color to see better, adjusting audio volume to hear better, or adjusting how text is presented to read it better.

**Comment by nitedog** [comment]
Changed as suggested.
