### ISSUE TITLE
[Input] Doesn't feel like the right content

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#277]
@nitedog, I can't recall now where we landed on the "Input" script, but this one feels like it's just copy/paste of the other scripts and doesn't include some of the really helpful key points from the written Tools & Techniques page. Also, the video includes Ilya and a repeat of screen readers when talking about keyboard navigation but this isn't in the written text. 

It feels like this really needs a rewrite (which I can help with). However, I can't recall how this was revised over time (not sure how to see prior versions) and I hope I'm not bringing up something we already discussed. 

Here's some more specific thoughts I had while reading for full context:
- This should focus more on the adaptations and less on the people. That is, reorder the content to say "people use X strategy" and then say "it's beneficial for Y people". Right now techniques that are used by many people are presented as only beneficial to a certain group.
- This should focus more on cognitive and physical disabilities and less on visual to help provide balance across the videos and generally overcome the "accessibility = blindness" misunderstanding people often have.
- This could/should more explicitly talk about adaptive hardware, even if in the video we just show the devices and not necessarily someone using them. For instance, this is a great place to talk about a switch and compare it with a keyboard and mouse.
- This should call out customizations as a nice intro to something people may not know, such as custom keyboard shortcuts. This might also have design implications for people trying to design keyboard shortcuts.
- It would be great to call out word prediction here as an AT here. People likely think it's just a nice-to-have and not know how vital it can be.

Those are some of my thoughts, not sure what the other comments have been (and I don't see a lot of comments from myself on this one). Again, happy to help craft a new approach even if it means meeting at an odd time to chat. (Almost started it but decided to just write out my thoughts for now.)

Btw, the current script says that blind people cannot use a touchscreen. That was probably unintentional (I think you were talking about in regards to a desktop) but want to be careful saying that of course since it can have negative implications for folks ([https://inews.co.uk/opinion/comment/visually-impaired-normal-lives-prejudice-mobile-phone-251895](https://www.google.com/url?q=https://inews.co.uk/opinion/comment/visually-impaired-normal-lives-prejudice-mobile-phone-251895&sa=D&source=docs&ust=1666473630830842&usg=AOvVaw2Qr22hvKAAmjF8XsT-QkQH)).

**Comment by nitedog** [comment]
> It feels like this really needs a rewrite (which I can help with)

@MicheleAWilliams-A11y please feel free to send any additional suggestions if you have them.

**Comment by MicheleAWilliams-A11y** [comment]
Hey @nitedog - wrote up a script with suggested visuals: https://docs.google.com/document/d/1cRQ6k8zDB1AcvVj54lLz5pQVTDPHC4rKYYgOXpGeupE/edit?usp=sharing

**Comment by nitedog** [comment]
Revised to incorporate the essence of these excellent suggestions.
