### ISSUE TITLE
[Visual] tunnel vision layout

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#280]
> Websites and apps that allow making text smaller but still keep the same page layout make it easier for the person to see more of the screen at one time.

I think (not sure) that ideal for person with tunnel vision and good visual acuity is to have all content in fairly small viewport so they can see more with less visual tracking. Or at least blocks of information in small area.

Thus, I'm not sure that "same page layout make it easier for the person to see more of the screen at one time" is accurate.

**Comment by nitedog** [comment]
Changed to:

> Websites and apps that can also adapt to smaller text sizes make it easier for people with tunnel vision to see more of the screen at one time.
