### ISSUE TITLE
[Visual] wording around colorblind

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#281]
> Finally, people with visual disabilities also includes people who see colors in a range of different ways, commonly referred to as colorblind. Often this means it can be hard for people to tell colors apart, so it’s important that websites and apps do not use just color to communicate information.

suggest:

> Some people cannot distinguish certain colors, often called “color blind”. So it’s important that websites and apps do not use only color to communicate information.

rationale: [style guide](https://www.w3.org/WAI/EO/wiki/Style#other_words_and_phrases) based on [LVTF discussion](https://github.com/w3c/low-vision-a11y-tf/discussions/121)

**Comment by nitedog** [comment]
Revised wording.
