### ISSUE TITLE
[Visual] contrast sensitivity - e.g,. gray text on white (& light sensitivity)

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#283]
> People who are colorblind might also adjust properties in the web browser or operating system, such as font color and style, to better distinguish text color from its background.

hum, I don't know how much changing text color and style is common among people who are colorblind?

I do know that changing background and text color is common among people with other types of low vision -- to address light/brightness sensitivity and low contrast sensitivity.

Also, many people who are older have low contrast sensitivity and have difficulty reading text with low contrast with its background, e.g., gray on white -- and do not know how to change colors. Thus WCAG SC 1.4.3 & 1.4.6.

I think this warrants it's own topic in this video.

refs:
* https://www.w3.org/WAI/test-evaluate/preliminary/#contrast
* https://www.w3.org/TR/low-vision-needs/#light-sensitivity
* https://www.w3.org/TR/low-vision-needs/#contrast-sensitivity
* https://www.w3.org/TR/low-vision-needs/#brightness-and-color

**Comment by nitedog** [comment]
Revised this entire section to:

> Some people cannot distinguish certain colors, often called "color blind". Websites and apps that avoid text with low contrast, such as gray text on white background, are easier to use for people who are color blind. It’s also important that websites and apps don't use only color to communicate information. In addition to color, websites and apps can use text and symbols, such as an asterisk to indicate required input fields. Some people are also sensitive to bright light, so it's important that websites and apps can adapt to color schemes people set in their browsers and operating systems.
