### ISSUE TITLE
[visual] intro text

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#284]
> Visual disabilities affect how people see, including seeing less in one or both eyes, not seeing, and seeing in a range of different ways.

doesn't see to cover it well.

I think it this warrants much more specificity -- especially to combat the common thinking that visual disabilities = totally blind.

Maybe along the lines of:
> Visual disabilities affect how people see, and there is a wide range of visual disabilities. Some people cannot see at all, they are blind. Some people who are legally blind have a little vision. Other visual impairments are more common than blindness. Some people have low vision and can’t read normal text. Some cannot distinguish certain colors (“color blind”). Some are bothered by bright light. Many older people have low contrast sensitivity and can’t see pale text.

**Comment by shawna-slh** [comment]
Probably also good to say something up front about that people with visual disabilities have very different user interface needs, depending on their visual condition.

**Comment by nitedog** [comment]
The suggested text is much longer and different in the approach we have taken for the other videos in this set. The point is to say something brief upfront, and elaborate on each of these examples in the later sections. This also better matches the visuals, as there isn't much to show in this intro piece but later on we can show the actual people when explain the different types of conditions.

I moved some of these aspects(e.g. "more common than blindness", sensitivity to brightness, etc.) further down in the body of the video and also adjusted the intro to the following:

> Visual disabilities affect how people see, including partial vision in one or both eyes, not seeing at all, and seeing in a range of different ways including colors and brightness.
