### ISSUE TITLE
[all] reduce repetition across videos, focus on category/topic of video

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#285]
There is a lot of repetition in the videos for Diverse Abilities and Barriers and the videos Tools and Techniques.

For example, this wording:
> People who are blind use assistive technology on computers and mobile phones called screen readers. These software tools can read the information on the screen out loud, or they can present the information in Braille using a device called a refreshable Braille display. Websites and apps with correctly coded headings, lists, links, button, and other structures can be better processed by screen readers. Websites and apps also need to work with keyboard, and have text alternatives for images, which are presented instead of the image

is almost exactly the same in [Diverse Abilities and Barriers, Visual script](https://wai-people-use-web-videos.netlify.app/people-use-web/videos/abilities/visual/) and [Tools and Techniques, Perception script](https://wai-people-use-web-videos.netlify.app/people-use-web/videos/tools/perception/)

Perhaps such repetition would be awkward, annoying, confusing - especially for those who watch all of the complications.
(Though possibly it's good for the occasion that someone watches only one video?)

I'm thinking there should be much less repetition, and each video should focus on the more relevant info for that topic. For example, perhaps:
* [Tools and Techniques, Perception script](https://wai-people-use-web-videos.netlify.app/people-use-web/videos/tools/perception/) includes "People who are blind rely on assistive technology on computers and mobile phones called screen readers. Screen readers are software that can read the information on the screen out loud. [and maybe even more about what screen readers can do, e.g., jump to headings!] They can also provide the information to a Braille display. Refreshable Braille displays raise and lower dots that people read with their fingertips." _[note: I think for this video, we can assume that people understand the gist of Braille.]_
* [Diverse Abilities and Barriers, Visual script](https://wai-people-use-web-videos.netlify.app/people-use-web/videos/abilities/visual/) says more succinctly: "People who are blind use screen reader software that reads the information on the screen out loud or provides it to a Braille display."

**Comment by nitedog** [comment]
I'll take another pass but this is a tough question. Do we expect people to binge watch ~1+ hours of video material? These repetitions are usually in different sets of videos, for example the description of screen reader appears in the story of Ilya, in Visual Disabilities, and in the video on Presentation. In each case screen readers are described in slightly different contexts but there is overlap and repetition to some degree. It seemed awkward to me to leave out the description of screen readers from each of these videos given how important screen readers are for digital accessibility. What are other opinions on this?

**Comment by lakeen** [comment]
I'm ok with the repetition. I think it's generally better to be more descriptive than to assume users know.  The  audience IMO for these videos are people who are new to web accessibility.

**Comment by bakkenb** [comment]
I am okay with some of the repetition as well. There will be overlap from both sets of videos when we are trying to define/describe a specific ability, tool, or technique that pertains to a specific population. Also, I agree that most likely someone will not binge all of the videos from all of these sets. If they do, I think it will be okay reinforcement to the novice audience.

**Comment by jade-mc** [comment]
I'm also fine with the repetition. I think it's good reinforcement, viewers are unlikely to notice that it's the same text, and that text has been really carefully crafted to ensure that it's clear and accessible in itself.

**Comment by shawna-slh** [comment]
> It seemed awkward to me to leave out the description of screen readers from each of these videos given how important screen readers are for digital accessibility.

Please note that I did not suggest to leave out description of screen readers from any of these videos. I suggested have more detailed description in some, and more succinct description in some.

**Comment by shawna-slh** [comment]
See discussion in [28 October 2022 EOWG minutes](https://www.w3.org/2022/10/28-eo-minutes.html#t06)

**Comment by MicheleAWilliams-A11y** [comment]
I would say I lean towards Shawn's sentiment of only using the language needed for each particular video. Thus, if a definition used in one video isn't fully needed for the context of another video, then don't copy it/use it just because it's what we came up with in the first video. 

But overall, it's easier to address this per video - e.g., if we're saying we want to streamline text then doing that in the view of the entire script. Without that, I wouldn't have a specific answer/opinion.

**Comment by nitedog** [comment]
I haven't read the minutes yet but which aspects, for example of a screen reader, would you say or not say in each of the videos? Any suggestions would help because I have difficulty reducing the repetition any further.

**Comment by nitedog** [comment]
Took another pass and did the best as I could to reduce repetition to the minimum necessary.
