### ISSUE TITLE
[Auditory] Various comments on first pass draft

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#29]
Overall like where this is going and I think it could be a good overview video for folks. 

As an overarching comment, I advocate we shy away from saying "they" (as in, "they rely on captions"). I fear this will perpetuate "othering" folks. I propose focusing on defining the condition/terms and introducing the technology and techniques in very matter of fact language that helps normalize the diversity.

With that here's a few more comments per scene...

- **Scene 1** - I suggest we more plainly explain the term "auditory" right off the top, as in "Auditory disabilities refers to not hearing clearly, or at all, in one or both ears."
- **Scene 2** - _"...they are commonly referred to as “hard of hearing”._ - As mentioned, I'm not opposed to identity-first language but here I think this would sound better to refer to the disability rather than the person and say "_this_ is commonly referred to as 'hard of hearing'".
- **Scene 3** - Maybe instead of "compensate" use "restore", as in "...don't fully restore a person's hearing..."
- **Scene 4 & 5** - Would reverse & combine these; we've not yet introduced the concept of multimedia (versus in-person conversation or hearing in general) so saying "the audio" here is a bit jarring (particularly for those who won't see the visuals).
Perhaps something like, "For online meetings and multimedia like videos, podcasts, and music, people who are hard of hearing rely on captions. These translate the important audio into text on the screen."
- **Scene 6** - I vote to remove; would like to keep this script to generalities about disability and AT approaches, but not AT specifics.
- **Scene 7** - While I can see also removing this point, I vote to keep this one because it flows better since auto-captions are likely top of mind for viewers.
- **Scene 8** - Perhaps call out that they sometimes lack punctuation and run sentences together? As in, "They don't recognize specialized terms and names, it's hard to tell who is speaking, and the sentences can sometimes run together making it hard to keep up. Having a person who can help clean up the text is vital to being able to follow along."
- **Scene 9 & 10** - I know this "volume"/"audio controls" part is in the current guides but they feel a bit outdated (because this is mostly how video players work now) and also a bit technical as only a few people are going to make the distinction between system and player/application audio controls. Do we feel strongly we need the "audio controls" part? How about, "Along with captions, people who are hard of hearing benefit from clear audio with reduced background noise; sometimes the music people use in their videos drowns out their talking."
- **Scene 11** - I would drop "uncorrectable" in this definition; some people eligible for Cochlear implants (i.e., with "correctable" hearing) choose not to get them. Maybe, "When people cannot make out clear sounds or any sounds at all, this is referred to as 'deaf'".
- **Scene 12** - No comment as is but see Scene 14 for possible addition.
- **Scene 13** - Maybe a transition to explain we're talking about remote communication? "They often require high-quality video transmissions for communicating in sign language [online/remotely]."
- **Scene 14** - _"They might not read as fluently..."_ I know what you mean but this might sound derogatory for some. I vote we leave this out anyway or combine with the prior scene and just say "For many people who are deaf, sign language is the primary language for communication. There are several sign languages worldwide and they are different than spoken and written languages."
- **Scene 15 & 16** - The current wording seems to imply signers don't use captions (especially with Scene 14 saying signers may not read fluently.) Perhaps, "People who are deaf also rely on captions as an alternative when sign language interpreters aren't available. Captions also help deaf people who do not use sign language, such as people who become deaf later in life."
- **Scene 17** - Needs a bit more transition and definition; I often find people have difficulty with "intersectionality" and thinking about multiple disabilities. Thus would suggest something like, "Finally, auditory disabilities include people who are deaf-blind, meaning people who have difficulty both hearing and seeing clearly, or at all. _[Possibly new scene]_ People who are deaf-blind use tactile sign language to communicate in-person, placing their hand on top of another person's hand to feel their signs. _[New scene]_ It's also important to provide transcripts for video and other multimedia that can be read on a Braille device _[shown in the video]_, as Braille-based text is the other primary communication method for a person who is deaf-blind."
- **Scene 18** -  Maybe something a bit more descriptive like, "Transcripts add to captions and provide all the details without having the watch a video, like including who was speaking and descriptions of the visual scenes."
- **Scene 19** - I like that! Wonder if we can use this for other videos (as in the sign-off Estella? mentioned).

**Comment by MicheleAWilliams-A11y** [comment]
Slight adjustment to my comments for Scenes 9 & 10 about the video player -- I noticed that YouTube doesn't have its own audio controls so perhaps the point about having a volume control in the player (rather than changing system audio) isn't as well known as it seems. However, I still wonder if it's a little too detailed for this script.

**Comment by jade-mc** [comment]
Hi Michelle, 
In scene 3, I'm not sure about changing compensate to restore, I think compensate is more accurate to encompass both hearing aids and cochlear implants. 
I'd also suggest keeping the thinking behind scene 14 in there somewhere, as it explains the fact that not all Deaf people can rely on captions. 
Suggest moving this idea up (perhaps re-worded) and combining it with scene 12, this might make more sense following on from there in terms of the order and flow. 
This also links to your point about scene 15 and 16, and I see where you're going here, but I think it's important to point out the misconception that SL users can't always 'just have the captions turned on and that's it'. In fact, maybe that point could go in 14 and then scenes 15 and 16 can stay as they are? 
I really like where the script is going too, especially the sign off.

**Comment by bakkenb** [comment]
In Scene 11, here are a couple of options to think about...
Original: "People with substantial and uncorrectable hearing loss in both ears are commonly referred to as “deaf”."
Option: "People with substantial or full hearing loss in both ears are commonly referred to as “deaf”."

Also wondering if we should change "deaf" to "Deaf" (capital D). In the US the Deaf community is usually offended by the lowercase title. I know this is the audio, but it will show in the captions. Not sure how this plays out in the rest of the world. I don't want this to become too US centric.

**Comment by jade-mc** [comment]
It's usually styled d/Deaf to encompass everyone.

**Comment by nitedog** [comment]
Addressed in latest revision.
