### ISSUE TITLE
[Input] scene 3

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#299]
I think scene 3 has a couple of issues, it could do with being simplified a bit and breaking down. 
I was going to try to edit it here, but then I realised, I don't actually understand what the second sentence is trying to say... I understand all of the elements of it, but at the moment it just reads like a list of items... I think there might be a typo or error in there somewhere. 
In the first sentence, definitely account for should be changed: 

Websites and apps also need to be **set up correctly for** people who use keyboard only. This includes providing ways to skip over repeated content, such as headers and navigation bars, as well as not breaking the default functionality in browsers and operating systems of using the Tab key to move around clickable items in the content, using the Enter key for selecting items, and showing a rectangular box known as focus indicator around the currently active item so that people can see which item is currently active. Websites and apps that provide word prediction and accelerators, for example for search terms, reduce the amount of required typing.

**Comment by nitedog** [comment]
Adjusted section for more clarity and flow, and propagated the related change for issue #300.
