### ISSUE TITLE
[Physical] Sequence 2 - active voice

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#300]
Two thing here in this sequence - going to focus more on the second...

First - There is an extra word or something off in the second sentence. Just needs to be copy edited for grammar.

Second - I think the last sentence should be using more active voice when describing the use of keys... See below:

Current:

> This includes not breaking the default functionality in browsers and operating systems of using the Tab key to move around clickable items in the content, using the Enter key for selecting items, and showing a rectangular box known as focus indicator around the currently active item so that people can see which item is currently active.

Recommended: (edits in bold/italic)

> This includes not breaking the default functionality in browsers and operating systems **_that use_** the Tab key to move around clickable items in the content, **_use_** the Enter key for selecting items, and **_show_** a rectangular box known as focus indicator around the currently active item so that people can see which item is currently active.

**Comment by nitedog** [comment]
Made changes as suggested.
