### ISSUE TITLE
beginning

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#321]
1. Logo &mdash; I think we want the W3C WAI logos and not the words in separate text. Probably in a banner across the lower part, like in the evaluation videos. (which echoes the WAI site header)
2. “How People with Disabilities Use Digital Technology” &mdash; How much emphasis on this phrase? Maybe less than the version from Wednesday 30 Nov?
3. name and phrase &mdash; Do we want this to be on the same view with “How People with Disabilities Use Digital Technology”, instead of a separate view?
4. montage &mdash; Maybe have montage at the beginning, too, to help communicate that this story is just one of many?

_perhaps first_
<img src="https://user-images.githubusercontent.com/6991814/204895091-14a7482c-94d1-4b79-9bbc-b3e2ca3acb8b.png" width ="369" />
 
_second_
<img src="https://user-images.githubusercontent.com/6991814/204895121-deb0c075-90cd-4e39-8481-b68c0c686f0c.png" width ="369" />

?

**Comment by iadawn** [comment]
1. Agree on logos... but the banner across the bottom only works if there is something in the middle. I am not sure about the big blue banner. It seems a bit 'presentationy'
2. Not sure on the emphasis... not done a comparison
3. Personally I like the separate slides
4. I really don't like this. I think the narrative starting with the individual and then showing that it is about people is much stronger.

**Comment by shawna-slh** [comment]
fyi, Perspectives video opening:
<img src="https://user-images.githubusercontent.com/6991814/204907145-c4559957-0ef2-4ac0-a8af-c2b180ede15c.png" width ="369" />

evaluation video opening:
<img src="https://user-images.githubusercontent.com/6991814/204908958-27881166-464f-43de-871e-641a4a66a472.png" width ="369" />

**Comment by shawna-slh** [comment]
1. logos &mdash; we don't have to have the logos on the first page. we could have them on the last page only. I don't feel strongly either way. (of course, we adjust the narration accordingly)
2.
3.
4. montage was just a brainstorm, I'm not for or against it. so happy to trash the idea since Kevin no likey

I do think that the current opening is pretty boring visually. *and* I also don't feel the need to spend energy fancying it up.

**Comment by iadawn** [comment]
Feedback sent to Kartoffel:

> - Audio when “Sophie” speaks seems to be balanced to the left rather than evenly stereo - I appreciate that this isn’t about the plates themselves but it was commented on by a few people.
> - Sliding the ‘How People with Disabilities use Digital Technology’ in from the left seems a bit peculiar and distracting.
> - 0:06 - the line should be “By the W3C Web Accessibility Initiative” - no quotes on ‘Web Accessibility’ and ‘initiative’ has a capital.
> - I think it would be worth keeping the ‘How People with Disabilities use Digital Technology’ for when the main video title appears. So leave the white block, fade out the ‘By the W3C…’ line and fade in the ‘Sophie’ line.
> - When ‘Sophie’ moves back into the grid of people, could you try moving her back into one of the four central squares. There was one comment that suggests this might reduce the movement and potential for too much distraction.
> - We need to get the W3C and the WAI logos in. Ideally with the ‘For more information’. The WAI logo isn’t actually an image, but can be grabbed from https://www.w3.org/WAI/.

**Comment by shawna-slh** [comment]
> 0:06 - the line should be “By the W3C Web Accessibility Initiative” - no quotes on ‘Web Accessibility’ and ‘initiative’ has a capital.

Sorry I wasn't clear. I think we do not want this text at all. We only want the logos. I think they can be at the bottom of the front plate and end plate fairly quietly.
