### ISSUE TITLE
[Videos] Collage black border or not?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-people-use-web-videos#323]
There are two styles for the collage at the start of some of the videos.

* No border (for example [Presentation video](https://app.frame.io/reviews/c87d88e0-58cf-4192-9ba8-57bfee7a96bf/247baf6c-7c79-4d84-a31d-f1ec446964ab)) - the opening collage does not include a border around individual videos.
* Border (for example [Navigation video](https://app.frame.io/reviews/c87d88e0-58cf-4192-9ba8-57bfee7a96bf/4a38e702-580f-4e3f-9466-8bd8845b2146) - the opening collage includes a small border around individual videos.

Do you have a preference?

**Comment by bakkenb** [comment]
I prefer the Border like in the Navigation opening collage. Easier to focus quickly and then listen to audio.

**Comment by shawna-slh** [comment]
strong +1 for border

**Comment by kakinney** [comment]
I prefer the border

**Comment by iadawn** [comment]
Going with bordered approach
