### ISSUE TITLE
[Auditory] Scene #7 - More descriptions/definitions for deaf-blind communication

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#35]
Suggest adding a bit more definition or description for this line: "Most people who are dead-blind rely on tactile means of communication, such as braille, tactile signing, and tadoma."

"Tactile signing" and "tadoma" in particular are very technical terms (I had to look up "tadoma"). Also, would suggest putting either tactile signing or tadoma in the video scenery as well (even if just for a few seconds).

**Comment by nitedog** [comment]
Addressed in latest revision.
