### ISSUE TITLE
[Auditory] scene 7

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-people-use-web-videos#39]
Review the following: "Transcripts include the captions as well as descriptions of the visual information in text format." A transcripts is a word-by-word text of the oral utterances made by the speaker, and do not include the visual information in text format. Usually transcripts are not time based files, so they are not linked to the media file.

**Comment by nitedog** [comment]
There might be different definitions for the term "transcript"? I was referring to the [WAI Media Tutorial](https://www.w3.org/WAI/media/av/transcripts/). I think WCAG refers to it as "[alternative for time-based media](https://www.w3.org/TR/WCAG22/#dfn-alternative-for-time-based-media)" but that seems too jargony to me.

**Comment by nitedog** [comment]
Addressed in latest revision.
