### ISSUE TITLE
[Martine] Seq. 3 Audio - Wording tweak

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#41]
Suggested wording change to help flow...

Current:

> This is more accurate than automatic captions, which don’t recognize specialized terms and names, it’s hard to tell who is speaking, and the sentences run together making it hard to keep up.

Proposed:

> This is more accurate than automatic captions, which don’t recognize specialized terms and names, **_make it_** hard to tell who is speaking, and **_can run sentences_** together making it hard to keep up.

**Comment by nitedog** [comment]
Addressed in latest revision.
