### ISSUE TITLE
[Martine] Seq. 5 Audio - Wording still not quite right

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#44]
There is something that is still not quite right about the wording of Sequence 5. I feel it does not convey that Martine's language is sign language and therefore reading is difficult, especially when it is with complex text. "constantly translating text into sign while I’m reading," does not convey that clearly. I think we need to simplify that somehow. Here is an attempt. Happy for others to weigh in on this.

> Of course, the classes also come with a whole lot of reading. I’m fine with that, except when the writing is unnecessarily complex and without structure like lists and headings. People don’t realize that I am constantly translating text into sign language that I process internally while reading, so I prefer clear and simple writing to make this task easier.

**Comment by nitedog** [comment]
I changed that last sentence to:

> People don't realize that I'm constantly translating text into sign, which is my primary language. So, like just about everyone else, I prefer clear and simple writing.

- repeating "my primary language" from earlier scene for emphasis
- kept "like just about everyone else" to be more inclusive

(keeping this issue open for further discussion)

**Comment by nitedog** [comment]
From sub-group discussion on 21 June:

> People don't realize that for me reading involves translating text into sign, which is my native language. So, just like for everyone else, clear and simple writing makes @@it/this task/reading@@ easier to understand.
