### ISSUE TITLE
[Martine] Slight change from "issues"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#46]
I think the script reads really well! There's a few typos but I won't use Github issues for that at this stage. Really I have just 1 comment about the last line where it says, "All these issues have one thing in common: your design can include or exclude people!" 

Looks like it was previously "them" instead of "people" and changed per Brent's comment but something about saying "all these **issues**" doesn't flow (leans negative). Is this what is was before (I can't recall)? Nonetheless, maybe just "All the ways I use technology have one thing in common" or something more neutral/matter-of-fact? I can keep thinking of feedback but wanted to get my comments in asap (didn't get a chance earlier in the day).

**Comment by nitedog** [comment]
Addressed in latest revision.
