### ISSUE TITLE
[Martine] a couple of comments

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#47]
Nothing major, the script is looking great! 
In scene 1 (and a later scene) 'primary language' is used, I think this should be changed to first or native language, there is a difference. 
Primary language is the main language someone uses to communicate, whereas native/first language is the one they were exposed to from birth. I think the latter describes Martine's situation. 
In scene 4, 'trying to lipread' rather than 'needing to lipread' might emphasise the point that it's unreliable. 
Also, suggest: 
_I also need to see the person’s face and have them speak slowly and clearly._ to
_I also need to make sure I can see all of the person's face so I can see thier expressions and even some gestures to help me understnand, and they need to speak slowly and clearly._

**Comment by jade-mc** [comment]
And sorry this wasn't with you yesterday, I've just got back from a week off!

**Comment by jade-mc** [comment]
As well as making sure I can see the person's lips clearly, it's also useful if I can see expressions and even some gestures to help me understand more.

**Comment by nitedog** [comment]
From sub-group discussion on 21 June:

- Change "primary" to "native", and open issue to get broader feedback from EO and beyond
- Removing "needing" (without "trying" either) for lip reading, and open issue for feedback
- Take another pass at adjusting the "exhausting" part (put it later in the scene)
- Consider "helpful to see facial expressions and gestures" to revise the sentence from above

**Comment by jade-mc** [comment]
I feel like I jumped in here, opened a can of worms, only attended half the meeting, and ran off! Sorry!

**Comment by nitedog** [comment]
Addressed in latest revision.
