### ISSUE TITLE
[Presentation] Seq. 2 - Wording of "hardware"

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#48]
To me when I see the term hardware I think of technology hardware like the computer cabinet, hard drive, processor, mother board, etc. I understand that the text is meant to say the physical tool used to magnify text like glasses or a magnifying glass, but I wouldn't use the term "hardware" to describe that.

Also one other edit to the end of the first sentence.

Current:

> Some people need further magnification and use specialized tools for that. These include hardware lenses and other visual aids, as well as software tools and functionality built into the operating system of the computer.

Recommended (but there may be better ways to say it):

> Some people need further magnification and use specialized tools **_to make adjustments_**. These include **_glasses or hand held_** lenses and other visual aids, as well as software tools and functionality built into the operating system of the computer.

**Comment by nitedog** [comment]
Changed to:

> Some people need further magnification and use specialized tools to make adjustments. These include hand held lenses and other visual aids, as well as software tools and functionality built into the operating system of the computer.

Rationale: the "glasses or" makes the sentence more difficult to parse and is redundant with "and other visual aids" later in the same sentence, so I removed it from the suggestion.
