### ISSUE TITLE
[Presentation] Seq. 1 - Alter wording to keep plain language

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#52]
The following sentence struck me as a little bit academic as well as a bit redundant: "This flexibility is essential for people with many types of disabilities, who might need particular types of presentation to better perceive the content."

I'll also add that using the word "users" might be a technical term (and one that some folks have started to take issue with just as an FYI).

Being overly mindful of using plain language for folks with cognitive disabilities (and those for whom English may not be their primary language), I wonder if we should say something like:

> One of the great things about digital technology – when it’s designed right – is that it allows people to change the way content is presented. Having options helps people with many types of disabilities.

**Comment by nitedog** [comment]
Changed as suggested.
