### ISSUE TITLE
[Presentation] Put more context/definition to "cognitive and learning disabilities"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#54]
While the text does a good job of grouping like examples/techniques together, overall this is a pretty broad category and it may be hard for a11y beginners to know why certain things are beneficial (such as "spacing of text"). 

Overall the opening sentences don't establish the disability impacts like with "visual disabilities" (where people need to see things larger) and "auditory disabilities" (where people need to hear things louder). Saying "...make text easier to read" (as it does currently) somewhat gets us there but could be stronger (or perhaps simply needs to move up sooner into the paragraph).

Overall I propose adding some examples of how a cognitive and learning disability impacts a person to help (1) distinguish between disabilities that aren't always related and (2) make the adjustments feel more applicable.

**Comment by nitedog** [comment]
Took a pass at this section but we need to further discuss it during today's meeting.

**Comment by nitedog** [comment]
Addressed in latest revision.
