### ISSUE TITLE
[Martine & Noor] refer to specific sign language?

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-people-use-web-videos#57]
I think you can just say "sign language is my native language" rather than specifying [British/American/TBD]

**Comment by nitedog** [comment]
This issue also applies to Noor.

**Comment by shawna-slh** [comment]
> I think you can just say "sign language is my native language" rather than specifying [British/American/TBD]

+1

> There was a counter suggestion that being more specific is more engaging.

maybe too subtle to make any difference

> It also signals to people new to the topic that there are many sign languages, just like spoken languages.

While that is interesting information, and people should understand that at some time in their learning, I think it's not an important point to get across for these videos. And, just mentioning one specific sign language likely won't be enough to educate most people.

> On the other hand, this further decreases the language-neutrality of the video (ie. decreases support for internationalization).

sure.

**Comment by iadawn** [comment]
Maybe be specific and general at the same time?

> As an American I speak American Sign Language – I think and dream in signs. There are many other sign languages though.

Or some such

**Comment by jade-mc** [comment]
+1 to Kevin's suggestion

**Comment by shawna-slh** [comment]
discussion in [30 September EOWG minutes](https://www.w3.org/2022/09/30-eo-minutes.html#t01)

**Comment by nitedog** [comment]
Change suggested by EO has been addressed in the [Auditory script](https://wai-people-use-web-videos.netlify.app/people-use-web/videos/abilities/auditory/) (see #231).
