### ISSUE TITLE
[Presentation] Sequence 1 - slight reword

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#66]
Current:

> One of the great things about digital technology – when it’s designed right – is that it allows people to change the way content is presented, to make the content easier to distinguish and understand.

Recommended: 

> One of the great things about digital technology – when it’s designed right – is that it allows people to change the way content is presented, _**making**_ the content easier to distinguish and understand.

**Comment by nitedog** [comment]
Changed as suggested.
