### ISSUE TITLE
[Presentation] Proposed script revisions

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#69]
Took a try at reducing and shuffling a few points. I think towards the end I added something fairly new/significant (highlighted below), otherwise this *should* just be a shorter version of the current script. With that, I believe most of the visuals can remain, though I didn't check that closely.

This removes 119 words and 1 minute of film [436 words, 3.4 minutes].

Of note, for the visual impairments section, the “reflow” portion was mentioned right after magnification which made it seem like they were related. This was moved (and shortened) closer to the applicable example. Also removed “reflow” since it can sound like jargon (and generally tried to stay away from jargon per our conversation today).

cc: @bakkenb, @eoncins, @jade-mc

---
A great thing about digital technology - when it’s designed right - is that people can change and customize the presentation for what works best for them.

For example, a person with a visual impairment might use larger text sizes to make content easier to read — setting this within the operating system of their computer or mobile device, or using a web browser’s font resize feature on individual websites. For these settings to work, apps, web browsers, and websites all have to be programmed and designed to respond to the increased fonts. Otherwise, text overlaps, gets cropped, or creates difficult scrolling.

For certain types of visual impairments, people increase everything on the screen through screen magnification software, which acts like a digital magnifying glass. It’s often also helpful to change the screen’s colors for more contrast (such as to primarily black and white or even blue and yellow) as well as use text-to-speech to hear the content while following it visually _[can pause narration here to allow hearing a screen reader]_. This again means applications and content must be able to adjust, rather than, say, hard coding colors and fonts to only appear a certain way.

Presentation is not just visual, however. People with auditory disabilities, for example, might need to increase the volume of online meetings and multimedia like videos, podcasts, and music — but without increasing the volume of other system sounds, like notification alerts. Adjusting the bass, treble, and balance can also make audio easier to hear — making it vital that operating systems and media players provide these settings.

Presentation adjustments can also make content easier to read and comprehend, particularly for people with cognitive and learning disabilities. This can include pop-up blockers and reduced motion settings to keep distractions minimal; web browser “reading modes” that hide less relevant page content; and virtual reading rulers to help readers focus on one line at a time.

Font types, sizes, colors, and spacing between letters and sentences can all make a difference in readability, such as when a person with Dyslexia changes a font style to what they can more easily see.

Then there are reading comprehension tools — such as tools that scan text and provide definitions for complex words and phrases, or even simplify complex sentences. 

This again highlights why it’s important to use flexible and customizable design, such as typing text in your social media post rather than just posting an image of text, and building in application features that allow users to adjust a variety of presentation settings. **[<-- This is the part where I took some liberties to help round out our suggestions so they didn't sound so redundant and also more specific.]**

No matter the part you play in digital technology, keep this one thing in mind: your choices can either include or exclude people. **[<--Trying to transition a bit more from our suggestions and also to acknowledge our various audiences - e.g., from content creators to product developers.]**

**Comment by MicheleAWilliams-A11y** [comment]
Awesome - looks great to me!

**Comment by bakkenb** [comment]
I am good with the version Michele has put forth here. The majority of the concepts are still in tact and a bit more succinct. I also think the addition of the background noise was seamless and easy to understand without adding much content.
