### ISSUE TITLE
[Presentation] typos

### ISSUE THREAD

**Issue by beltonTPG** [w3c/wai-people-use-web-videos#73]
Typo in summary - "(#2) uses screen magnification, high-contrast, and text-to-speech (this person will likely also be featrued in the script for Visual page" (featured is misspelled). Also the phrase "featured in the script for Visual page" doesn't really make sense. Perhaps it should be "featured in the script for Visual disabilities"?

Typo is summary - "(#3) uses hearing aid and increased audio volume (this person was featrued in the Auditory script" (featured is misspelled).

Content-wise, it is good.

**Comment by nitedog** [comment]
Typos fixed as suggested.
