### ISSUE TITLE
[Martine] See Martine more?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#76]
Just wondering aloud if we should see Martine's "documentary/talking head" view a few more times within the video as it transitions between the scenes. Something I'm sure the video crew will help with but as I imagined this, just felt a shame to only see her directly communicating with us twice even though she's the subject of the other scenes.

**Comment by nitedog** [comment]
Good point. Will convey this style request to the video professionals -- that we want the audience to "connect" with Martine but would like to leave the specific camera work to their expertise.

**Comment by nitedog** [comment]
Closing this issue, please re-open if you feel your comments have not be addressed adequately.
