### ISSUE TITLE
[Auditory] Better transition of topics needed

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#77]
The transition from defining auditory disabilities then talking about hearing aids and cochlear implants has a jarring transition to captions - they don't feel connected. Also, the order that the first two scenes are presented doesn't quite flow.

Here's some suggestions:

> Auditory disabilities refers to impacts on hearing such as hearing sounds differently, not hearing below certain volumes, or not hearing any sounds at all. 
> 
> While some people may use hearing aids or have cochlear implants to help with understanding speech, these often don’t fully compensate for auditory disabilities. _[Suggest removing "especially with background noise" as this (1) can come through with the scene, (2) represents a problem everyone has with hearing in a loud room, and (3) over-emphasizes in-person interactions when the main point is to talk about digital/Web presentations.]_
> 
> Thus, for online meetings and digital content like videos, podcasts, and music, people with auditory disabilities of all types rely on captions....

**Comment by nitedog** [comment]
Changed:

> Some people with auditory disabilities can hear sounds but not sufficiently to understand all speech. Cochlear implants and other hearing aids often don’t fully compensate for auditory disabilities, especially when there is background noise.

To:

> Some people use hearing aids or have cochlear implants to improve their hearing. However, these often don’t fully compensate for auditory disabilities.

**Comment by nitedog** [comment]
Relates to #80 and #83

**Comment by MicheleAWilliams-A11y** [comment]
Hey, just want to make sure it's not lost that this was initially meant to talk about the general pattern of the videos - it just so happened to relate to the other tickets around cochlear implants. 

I believe we can better define auditory disabilities (first sentence) since the phrase "auditory disability" (and specifically the more academic word "auditory") may be unfamiliar to folks. 

Also I propose the order of examples should progress differently (e.g., moving from some to all hearing loss) but that's not as big an issue.

**Comment by nitedog** [comment]
Thanks for catching this @MicheleAWilliams-A11y!

Side note: in the future, it may be better to open a separate issue for each comment so that none get lost.

1: On explaining "auditory disabilities", currently the text reads as follows:

> There are many forms of auditory disabilities, including people who have reduced hearing, do not hear, or hear sounds differently.

Your proposed wording is:

> Auditory disabilities refers to impacts on hearing such as hearing sounds differently, not hearing below certain volumes, or not hearing any sounds at all.

I'm a bit concerned about "impacts" because it seems a little medical and about "below certain volumes" because it seems a little simplistic. I also miss the "many forms of auditory disabilities". Can you say a little more why the current approach doesn't explain auditory disabilities well enough in your view?

2: Currently we start by a person (1) who can partially hear, then a person (2) who uses captions, then a person (3) who can partially hear, then a person (4) who uses sign, then a person (5) who uses braille. Are you proposing we switch the order of person 2 and person 3?

**Comment by MicheleAWilliams-A11y** [comment]
1. Saying "There are many forms of [x]..." presumes you are coming in with some knowledge [x] and being given examples (subsets of it). Saying "[x] is..." defines the term itself while also leaving room for examples in the next phrase or sentence. 

2. I was not relating this to the presentation of the people in the video (and it's not likely the viewers will either). Just felt off to list essentially "some hearing", "no hearing", then "some hearing" again. Felt there should be a progression from "some" to "none" when listing the examples.

**Comment by nitedog** [comment]
1. Changed to "Auditory disabilities includes people who have reduced hearing, do not hear, or hear sounds differently."
2. Are you suggesting we move scene 5 (adjusting hearing aid volume) to after scene 2 (difficulty hearing in loud environment)?

**Comment by MicheleAWilliams-A11y** [comment]
1. That feels clearer to me and addresses what I was flagging.
2. No. My initial point about the flow of opening paragraphs looks like it's been addressed with the recent changes as well. I'll close this one - thanks!
