### ISSUE TITLE
[Presentation] Sign Language and Symbols

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#78]
In re-reading the "Presentation" guide, we don't mention Sign Language or Symbols - two which I think would be important to cover. In addition, our "reading assistants" take up 3 scenes and a lot of text - seems we can reduce this down to maybe even one scene to make room for some other examples. If we agree on this I can help swap text and keep things succinct.

**Comment by nitedog** [comment]
Relates to https://github.com/w3c/wai-people-use-web/issues/233

**Comment by nitedog** [comment]
During the [meeting of 29 July 2022](https://www.w3.org/2022/07/29-eo-minutes#item01) EOWG decided to:

1. Move sign language to be predominantly on the "Perception" page and video
2. Have symbols mentioned in both the "Perception" and "Presentation" pages
3. Have symbols be shown in the "Perception" video (eg. as a reading modality)
4. Keep this issue open and revisit this when the related videos are more mature

**Comment by bakkenb** [comment]
See discussion in [28 October 2022 EOWG minutes](https://www.w3.org/2022/10/28-eo-minutes.html#item07)
