### ISSUE TITLE
[Martine] changing position of video captions

### ISSUE THREAD

**Issue by Sylvie42** [w3c/wai-people-use-web-videos#79]
Hello,

I have two issues with the script:

1. In the script, following sentence may be not clear:

> "For this, I need meeting apps with functionality to “pin” videos of the interpreters".

Not sure if the word "meeting" is clear enough. 

Proposal: may be add "apps for on-line meetings" or "apps for videoconference meetings"?

**Note**: this is not essential, but editor's discretion.  

2. In the [document describing Martine](https://deploy-preview-113--wai-people-use-web.netlify.app/people-use-web/user-stories-six/), there is following sentence:
>
> "Works well: “Captions appear at the bottom of the screen against a solid color background that offers good contrast between the captions and background.”"

The problem she encounters is:
>
> "the captions often appear on top of the video. This obscures the video and makes the captions hard to read over a background that is constantly changing.”"

From the script, sequence 0:35 to 1:15, I understand that the opposite is said in the description of visuals:
>
> "We also see Martine moving the captions above the video where she can see them better."

**Comment by nitedog** [comment]
Related comment from @AndrewArch 

> Scene 2 - should "meeting apps" be "video conferencing apps"? This emphasises that it is video, not just audio.

**Comment by nitedog** [comment]
1. Changed scene 2 as suggested by Andrew
2. Opened issue https://github.com/w3c/wai-people-use-web/issues/236 to address second point

**Comment by nitedog** [comment]
Closing this issue, please re-open if you feel your comments have not be addressed adequately.
