### ISSUE TITLE
Recording style - TikTok-like

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#8]
In an EOWG discussion a few weeks ago, there was an idea to have the style be self-recorded - e.g., TikTok etc.

One benefit to that is more flexibility for recording, that is, we could have less professional recordings of the "protagonists".

(I'm not necessarily in favor of that -- just putting it here so it doesn't get lost.)

**Comment by jade-mc** [comment]
I think it's a great idea. I think it might be nice to play with different formats, even within the same resource, it will add some realism to the piece.

**Comment by nitedog** [comment]
Short: Frankly, I don't feel that I have the necessary skills for this. Happy to work with anyone else who can lead this.

Longer: It is difficult enough recruiting people with the matching types of profiles for this, let alone people who feel comfortable enough speaking and acting to some degree. This format would require people who also have the skills and capacity to record themselves in adequate quality as well. We would also require a production company that has the experience in working with such formats, and I don't know how difficult or easy that would be. In addition to all this, we are not certain that this proposed format would work well either. This seems like a lot and effort and a lot of risk, with limited time and resources. Again, really happy to step aside if someone else has the skills and vision for this!

**Comment by haltersweb** [comment]
In considering the longevity of these videos I'd suggest not doing a TikTok format because it will go out of style.  Classic style would have the longest longevity without people in 5 years rolling their eyes LOL!

**Comment by jade-mc** [comment]
I guess by TikTok style it's more about the self made aspect where people upload their own videos to social media. The only reason I raised it initially is because whenever I work on stuff like this it's always from a perspective of having no budget (so we often have to be quite creative with the content we produce at the OU.)

**Comment by bakkenb** [comment]
I agree that there is a lot of risk with trying a new format like this. Without experience of how this would work and finding the right people to do it, I think better off going with well produced videos similar to Perspectives videos.
