### ISSUE TITLE
tagline!

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#81]
current draft:
> All this has one thing in common: your design can include or exclude people.

I'm tickled to see an overall tagline, given the overwhelming success of "Web accessibility: Essential for some, useful for all." on the perspective videos.

I've assigned myself to work on ideas for strengthening the tagline. Feel free to nag me about it. :)

**Comment by nitedog** [comment]
Thanks Shawn, I was hoping to invoke your skills! Please see some brainstorms in issue #55 already. Closing this for now.
