### ISSUE TITLE
Martine scene 1

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#9]
Sorry if this has been discussed or if I'm missing somethign obvious, but why do we need an interpreter on the side? Surely that's common practice for the other way round? So spoken language on screen with an interpreter conveying the sign to an audience... 
Would the audio voice over be enough?

**Comment by nitedog** [comment]
Addressed.

Background: The interpreter is not signing to the audience. In this scene, we see Martine for the first time. She is signing to us, the viewers. We also get a glimpse of how she does interviews by seeing the sign language interpreter. We understand that the voice we hear is not hers but that of the interpreter. The the documentary-style video continues with other scenes.
