### ISSUE TITLE
[Navigation] Scene 2

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#93]
In scene 2, I think low vision might be problematic to include here, thinking of people with a low level of knowledge who are visiting the page for info might benefit from this being separated out.
Suggest: People who are blind or have very low vision, use a screenreader to navigate the content on the screen. They use this to scan the content structures and headings to get an overview and orient themselves. This means that the content structures such as navigation menus and sidebars need to be properly and consistently labelled, and long passages of text…

**Comment by nitedog** [comment]
This entire script has been heavily edited; please re-review.
