### ISSUE TITLE
[Navigation] Scenes 6 and 7

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-people-use-web-videos#94]
Suggest moving scene 7, followed by 6, to the beginning of the script to set the context more effectively, if this happens, they’ll need a bit of tweaking. 
I see that scene 6 is drawn from the final bulletpoint in the list on the navigation page, I don’t think this sits well alongside the other scenes (which speak about a particular category of disability.) 

Side point, I don't have any comments for the Input script btw, it looks good to me for now, all info flowing really nicely.

**Comment by nitedog** [comment]
This entire script has been heavily edited; please re-review.
