### ISSUE TITLE
[Input] Scene 2 - "Cognitive" is out of place

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#95]
Currently reads - "For example, some people with certain types of cognitive, neurological, and physical disabilities have limited hand movement or control."

Cognitive impairments in themselves wouldn't impact hand movement and control; this isn't the right combination of characteristics/descriptions.

**Comment by nitedog** [comment]
Removed from the script (note that the actual reference page mentions this).
