### ISSUE TITLE
[Input] Put a tip after every item

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#96]
We go through 5 scenes of AT examples before we get to the point that systems need certain designs in order to work. I think we should better (more explicitly) guide users to the takeaways from each AT demo - otherwise people may do things like pity the video subject for having to "type like that". 

I propose that each demo have a pattern such as: 
- name of tool or technique
- how it works
- who it's for
- considerations for it 

The considerations can then be WCAG-like tips for design & code, or simply more explanation of what makes the item more efficient such as using a built-in feature to maximize it. We can also bring up what makes things barriers, but again I would do that directly after introducing the AT.

**Comment by nitedog** [comment]
This entire script has been heavily edited; please re-review.
