### ISSUE TITLE
[Navigation] Propose a different focus

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-people-use-web-videos#98]
I have a somewhat radical proposal to flip the focus of this video and highlight the Website techniques rather than the people. I mostly say this because almost everyone benefits from things like headings and consistent page layout; it's going to be hard to separate (or combine) disabilities to describe the benefits because they'll usually benefit a great number and diversity of people. This video is also starting to feel the same as the other videos in this new set and they should be feeling different.

I wonder instead if have some graphics/visuals of building out a page from blank canvas to a wireframe to a final page? That is, use something like a [skeleton website](https://i.pinimg.com/originals/b3/fd/01/b3fd0117c27bda501f58541c80e733a3.jpg) to highlight things like headings, structure, and even placement of a Skip Link. 

Then we're explaining in the narration (and maybe supplemental on-screen text) benefits like how Headings help with organizing information and building out the structure (calling out screen readers in particular here), clear navigation structures help people target their tasks (calling out cognitive impairments such as memory deficits here), and keeping the same easy-to-see/distinguish design patterns throughout the pages reduces cognitive load (calling out how the benefits everyone).

**Comment by nitedog** [comment]
This entire script has been heavily edited; please re-review.
