### ISSUE TITLE
[Perception] Scene 4 - Opening jumps from previous scene

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-people-use-web-videos#99]
In scene 3 we are introduced to screen readers. Then the majority of the rest of the script is the output to a braille display. Then when scene 4 starts it says "However, for screen readers to work," it is a little bit of a jolt or jump back into "oh yeah, we were just hearing about screen readers, I forgot."

Need some smoother transition between scene 3 and 4.

**Comment by nitedog** [comment]
Reduced the description on braille and removed the "however" to help further smooth the transition. Hope this works now?
